-- Explicit-allowlist SKD / OFC master search tables.
-- Fresh installations should run this file before deploying sync-master-data.

create extension if not exists pg_trgm;

create table if not exists public.skd_master (
  id bigint generated by default as identity primary key,
  source_row integer not null unique,
  source_no text not null default '',
  style text not null default '',
  page_number text not null default '',
  name text not null,
  reading text not null default '',
  type_label text not null default '',
  skill text not null default '',
  limit_text text not null default '',
  timing text not null default '',
  target text not null default '',
  range_text text not null default '',
  difficulty text not null default '',
  confrontation text not null default '',
  description text not null default '',
  search_text text not null default '',
  sync_token uuid not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.ofc_master (
  id bigint generated by default as identity primary key,
  source_row integer not null unique,
  page_number text not null default '',
  major_category text not null default '',
  minor_category text not null default '',
  manufacturer text not null default '',
  name text not null,
  site_category text not null default 'other' check (site_category in ('weapon','armor','cyberware','tron','vehicle','residence','other')),
  purchase_target text not null default '',
  permanent_cost text not null default '',
  concealment text not null default '',
  concealment_penalty text not null default '',
  attack text not null default '',
  parry text not null default '',
  range_text text not null default '',
  speed text not null default '',
  control_value text not null default '',
  electronic_control text not null default '',
  defense_s text not null default '',
  defense_p text not null default '',
  defense_i text not null default '',
  slot text not null default '',
  description text not null default '',
  raw_data jsonb not null default '{}'::jsonb,
  search_text text not null default '',
  sync_token uuid not null,
  updated_at timestamptz not null default now()
);

-- Only UIDs explicitly inserted here may search SKD / OFC.
create table if not exists public.master_search_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  memo text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists skd_master_style_idx on public.skd_master(style);
create index if not exists skd_master_type_idx on public.skd_master(type_label);
create index if not exists skd_master_name_idx on public.skd_master(name);
create index if not exists skd_master_search_trgm_idx on public.skd_master using gin(search_text gin_trgm_ops);

create index if not exists ofc_master_site_category_idx on public.ofc_master(site_category);
create index if not exists ofc_master_major_idx on public.ofc_master(major_category);
create index if not exists ofc_master_minor_idx on public.ofc_master(minor_category);
create index if not exists ofc_master_name_idx on public.ofc_master(name);
create index if not exists ofc_master_search_trgm_idx on public.ofc_master using gin(search_text gin_trgm_ops);

alter table public.skd_master enable row level security;
alter table public.ofc_master enable row level security;
alter table public.master_search_users enable row level security;

revoke all on table public.skd_master from anon;
revoke all on table public.ofc_master from anon;
revoke all on table public.master_search_users from anon;
revoke all on table public.skd_master from authenticated;
revoke all on table public.ofc_master from authenticated;
revoke all on table public.master_search_users from authenticated;

grant select on table public.skd_master to authenticated;
grant select on table public.ofc_master to authenticated;
grant all on table public.skd_master to service_role;
grant all on table public.ofc_master to service_role;
grant all on table public.master_search_users to service_role;
grant usage, select on sequence public.skd_master_id_seq to service_role;
grant usage, select on sequence public.ofc_master_id_seq to service_role;

create or replace function public.can_use_master_search()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.master_search_users allowed
      where allowed.user_id = auth.uid()
    );
$$;

revoke all on function public.can_use_master_search() from public;
revoke all on function public.can_use_master_search() from anon;
grant execute on function public.can_use_master_search() to authenticated;

drop policy if exists skd_master_authenticated_select on public.skd_master;
drop policy if exists skd_master_allowed_select on public.skd_master;
create policy skd_master_allowed_select
on public.skd_master
for select
to authenticated
using (public.can_use_master_search());

drop policy if exists ofc_master_authenticated_select on public.ofc_master;
drop policy if exists ofc_master_allowed_select on public.ofc_master;
create policy ofc_master_allowed_select
on public.ofc_master
for select
to authenticated
using (public.can_use_master_search());

comment on table public.skd_master is 'SKD search master. Only explicitly allowed authenticated UIDs may read; service role synchronizes source data.';
comment on table public.ofc_master is 'OFC search master. Only explicitly allowed authenticated UIDs may read; service role synchronizes source data.';
comment on table public.master_search_users is 'Explicit UID allowlist for SKD / OFC master search.';
comment on function public.can_use_master_search() is 'Returns true only when the current authenticated UID is registered in master_search_users.';
