/* Legacy character-sheets JSON import for the sheet editor. */
(()=>{
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const dialog=$('#legacy-import-dialog'),open=$('#legacy-import-open'),copy=$('#legacy-bookmarklet-copy'),apply=$('#legacy-import-apply'),text=$('#legacy-import-json'),msg=$('#legacy-import-message');
if(!dialog||!open||!apply)return;
const exporter=`javascript:(()=>{const label=e=>{const id=e.id;const l=id&&document.querySelector('label[for="'+CSS.escape(id)+'"]');return(l?.innerText||e.closest('label')?.innerText||e.closest('th,td')?.innerText||'').trim()};const section=e=>{let n=e;while(n&&n!==document.body){const h=n.querySelector?.(':scope>h1,:scope>h2,:scope>h3,:scope>legend');if(h)return h.innerText.trim();n=n.parentElement}return''};const fields=[...document.querySelectorAll('input,select,textarea')].filter(e=>!['button','submit','password'].includes(e.type)).map(e=>({id:e.id||'',name:e.name||'',type:e.type||e.tagName.toLowerCase(),value:e.type==='checkbox'||e.type==='radio'?(e.checked?e.value||true:false):e.value,checked:!!e.checked,label:label(e),section:section(e)}));const data={format:'tnx-character-sheets-v1',url:location.href,exportedAt:new Date().toISOString(),title:document.title,fields};const out=JSON.stringify(data,null,2);navigator.clipboard.writeText(out).then(()=>alert('キャラシJSONをコピーしました。')).catch(()=>prompt('JSONをコピーしてください',out));})();`;
const wait=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
const cleanName=value=>String(value||'').trim().replace(/^[★†※■┗]+\s*/,'').replace(/Ｎ◎ＶＡ/g,'N◎VA');
const parseCastName=value=>{const raw=String(value||'').trim();const match=raw.match(/^[\s　]*[“”"「『](.+?)[“”"」』][\s　]*(.+)$/);return match?{handle:match[1].trim(),name:match[2].trim()}:{handle:'',name:raw}};
const number=value=>{const match=String(value??'').match(/-?\d+/);return match?Number(match[0]):0};
const truth=value=>String(value??'').trim()!==''&&String(value)!=='0'&&value!==false;
const setElement=async(selector,value,event='input')=>{const element=$(selector);if(!element||value===undefined||value===null)return false;element.value=String(value);element.dispatchEvent(new Event(event,{bubbles:true}));if(event!=='change')element.dispatchEvent(new Event('change',{bubbles:true}));await wait();return true};
const click=async selector=>{const element=$(selector);if(!element)return false;element.click();await wait();return true};
const fieldMap=data=>new Map(data.fields.map(field=>[field.id,String(field.value??'')]));
const get=(map,id)=>map.get(id)||'';
const groups=(map,prefix)=>{const output=new Map();for(const [id,value] of map){const match=id.match(new RegExp('^'+prefix.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\.([^.]*)\\.(.+)$'));if(!match)continue;const [,index,key]=match;if(!output.has(index))output.set(index,{});output.get(index)[key]=value}return [...output.values()]};
const setInput=async(element,value)=>{if(!element)return;element.value=String(value??'');element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}));await wait()};
const rowName=row=>cleanName(row?.querySelector('[data-f="name"]')?.value);
const findRow=(area,name)=>$$(`${area} tr[data-skill-key]`).find(row=>rowName(row)===cleanName(name));
async function clearRows(selector,filter=()=>true){for(const row of $$(selector).filter(filter)){const del=row.querySelector('[data-delete-skill],[data-delete-outfit]');if(del){del.click();await wait()}}}
const findSkillGroup=label=>[...document.querySelectorAll('#general-skills .skill-group')].find(group=>(group.querySelector('.skill-group-title')?.textContent||'').includes(label));
async function clearSkillGroup(label){let guard=0;while(guard++<30){const group=findSkillGroup(label);const row=group?.querySelector('tbody>tr[data-skill-key]');if(!row)break;const del=row.querySelector('[data-delete-skill]');if(!del)break;del.click();await wait()}}
async function clearInitialSocialAndConnections(){await clearSkillGroup('社会');await clearSkillGroup('コネクション')}
async function setSkillRow(row,data,kind){if(!row)return;const key=row.dataset.skillKey;const locate=()=>document.querySelector(`tr[data-skill-key="${CSS.escape(key)}"]`);
let current=locate();await setInput(current?.querySelector('[data-f="name"]'),cleanName(data.name));
current=locate();const type=current?.querySelector('[data-f="skill_kind"]');if(type){type.value=kind;type.dispatchEvent(new Event('input',{bubbles:true}));await wait()}
const suits={reason:truth(data.s),passion:truth(data.c),life:truth(data.h),mundane:truth(data.d)};const suitCount=Object.values(suits).filter(Boolean).length;const level=Math.max(0,number(data.level));
current=locate();const levelElement=current?.querySelector('[data-f="level"]');if(levelElement){levelElement.value=String(level);levelElement.dispatchEvent(new Event('input',{bubbles:true}));await wait()}
for(const [suit,on] of Object.entries(suits)){current=locate();const box=current?.querySelector(`[data-f="${suit}"]`);if(box&&box.checked!==on){box.checked=on;box.dispatchEvent(new Event('input',{bubbles:true}));await wait()}}
if(level!==suitCount){current=locate();const element=current?.querySelector('[data-f="level"]');if(element){element.value=String(level);element.dispatchEvent(new Event('input',{bubbles:true}));await wait()}}
current=locate();const description=current?.querySelector('[data-f="description"]');if(description){const detail=[data.skill&&`技能：${data.skill}`,data.limit&&`上限：${data.limit}`,data.timing&&`タイミング：${data.timing}`,data.target&&`対象：${data.target}`,data.range&&`射程：${data.range}`,data.aim&&`目標値：${data.aim}`,data.confront&&`対決：${data.confront}`,data.notes].filter(Boolean).join('\n');await setInput(description,detail)}
}
async function addSkill(button,area,data,kind){const before=new Set($$(`${area} tr[data-skill-key]`).map(row=>row.dataset.skillKey));await click(button);const row=$$(`${area} tr[data-skill-key]`).find(candidate=>!before.has(candidate.dataset.skillKey));await setSkillRow(row,data,kind)}
async function importStyles(data,map){const outline=get(map,'outline')||data.fields.find(field=>field.id==='outline')?.value||'';const names={Katana:'カタナ',Vasara:'バサラ',Hiruko:'ヒルコ',Kabuki:'カブキ',Tatara:'タタラ',Mistress:'ミストレス',Kabuto:'カブト',Charisma:'カリスマ',Mannequin:'マネキン',Kaze:'カゼ',Fate:'フェイト',Kuromaku:'クロマク',Exec:'エグゼク',Kugutsu:'クグツ',Kage:'カゲ',Chakra:'チャクラ',Legger:'レッガー',Kabutowari:'カブトワリ',Highlander:'ハイランダー',Mayakashi:'マヤカシ',Talkie:'トーキー',Inu:'イヌ',Neuro:'ニューロ',Common:'コモン',Kurogane:'クロガネ',Ibuki:'イブキ',Shikigami:'シキガミ',Arashi:'アラシ',Kagemusha:'カゲムシャ',Migiude:'ミギウデ',Etranger:'エトランゼ',Ayakashi:'アヤカシ',Utsuwa:'ウツワ'};
const parts=String(outline).split(',').map(value=>value.trim()).filter(Boolean);for(let index=0;index<3;index++){const raw=parts[index]||'',mark=raw.includes('◎')&&raw.includes('●')?'◎●':raw.includes('◎')?'◎':raw.includes('●')?'●':'';const token=raw.replace(/[◎●□\s]/g,'');const name=names[token]||token;if(name)await setElement(`#style-${index+1}`,name,'change');await setElement(`#style-${index+1}-mark`,mark,'change')}}
async function importAbilities(map){for(const key of ['reason','passion','life','mundane']){await setElement(`#${key}-base`,number(get(map,`ability.${key}.abl`)));const control=get(map,`ability.${key}.ctl`),numbers=(control.match(/-?\d+/g)||[]).map(Number),base=numbers[0]||0,final=numbers[1]??base;await setElement(`#${key}-control-base`,base);await setElement(`#${key}-control-mod`,final-base)}await setElement('#cs-base',number(get(map,'ability.cs')))}
async function importGeneral(map){const fixed=new Set(['医療','射撃','知覚','電脳','製作：','心理','自我','交渉','芸術：','運動','回避','白兵','操縦：','信用','圧力','隠密']);await clearRows('#general-skills .skill-group:first-child tr[data-skill-key]',row=>!fixed.has(rowName(row)));
for(const data of [...groups(map,'skills1'),...groups(map,'skills2')]){const name=cleanName(data.name);if(!name||!number(data.level))continue;let row=findRow('#general-skills .skill-group:first-child',name);if(row)await setSkillRow(row,{...data,name},name.includes('：')?'proper':'general');else await addSkill('#add-general','#general-skills .skill-group:first-child',{...data,name},name.includes('：')?'proper':'general')}
for(const data of groups(map,'skills3')){if(!cleanName(data.name)||!number(data.level))continue;await addSkill('#add-social','#general-skills .skill-group:nth-child(2)',data,'proper')}
for(const data of groups(map,'skills4')){if(!cleanName(data.name)||!number(data.level)||/^ー+$/.test(cleanName(data.name)))continue;await addSkill('#add-connection','#general-skills .skill-group:nth-child(3)',data,'proper')}}
async function importStyleSkills(map){await clearRows('#style-skills tr[data-skill-key]');for(const data of groups(map,'superhumanskills')){const name=cleanName(data.name),level=number(data.level);if(!name||!level||String(data.name||'').trim().startsWith('■'))continue;const cost=number(data.expbase),kind=cost>=50?'ultimate':cost>=20?'secret':'normal';await addSkill('#add-style-skill','#style-skills',{...data,name},kind)}}
async function addOutfit(category,data){const before=new Set($$('#outfit-list [data-outfit-key]').map(card=>card.dataset.outfitKey));await click('#add-outfit');let card=$$('#outfit-list [data-outfit-key]').find(candidate=>!before.has(candidate.dataset.outfitKey));if(!card)return;const key=card.dataset.outfitKey,locate=()=>document.querySelector(`[data-outfit-key="${CSS.escape(key)}"]`);let current=locate();await setInput(current?.querySelector('[data-o="category"]'),category);current=locate();await setInput(current?.querySelector('[data-o="name"]'),data.name);current=locate();await setInput(current?.querySelector('[data-o="purchase_value"]'),number(data.purchase));current=locate();await setInput(current?.querySelector('[data-o="experience_cost"]'),number(data.permanent));current=locate();const conceal=[data.concealA,data.concealB].filter(value=>String(value??'')!=='').join('/');await setInput(current?.querySelector('[data-o="concealment"]'),conceal);current=locate();await setInput(current?.querySelector('[data-o="attack"]'),data.attack||'');current=locate();const defense=[data.protecS,data.protecP,data.protecI].filter(value=>String(value??'')!=='').join('/');await setInput(current?.querySelector('[data-o="defense"]'),defense);current=locate();await setInput(current?.querySelector('[data-o="range"]'),data.range||'');current=locate();await setInput(current?.querySelector('[data-o="slot"]'),data.part||data.slot||'');current=locate();const description=current?.querySelector('[data-o="description"]');if(description)await setInput(description,data.notes||'')}
async function importOutfits(map){await clearRows('#outfit-list [data-outfit-key]');for(const data of groups(map,'weapons'))if(cleanName(data.name))await addOutfit('weapon',data);for(const data of groups(map,'armours'))if(cleanName(data.name)&&number(data.permanent)>0)await addOutfit('armor',data);for(const data of groups(map,'outfits'))if(cleanName(data.name))await addOutfit('other',data);for(const data of groups(map,'vehicles'))if(cleanName(data.name))await addOutfit('vehicle',data);for(const data of groups(map,'residences'))if(cleanName(data.name))await addOutfit('residence',data)}
open.addEventListener('click',()=>{msg.textContent='';dialog.showModal()});
copy?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(exporter);msg.textContent='ブックマークレットをコピーしました。'}catch{msg.textContent='コピーに失敗しました。ブラウザの権限を確認してください。'}});
apply.addEventListener('click',async()=>{apply.disabled=true;msg.textContent='JSONを変換しています…';try{const data=JSON.parse(text.value);if(data.format!=='tnx-character-sheets-v1'||!Array.isArray(data.fields))throw new Error('対応する旧キャラシJSONではありません');const map=fieldMap(data);
await clearInitialSocialAndConnections();
const castName=parseCastName(get(map,'base.name'));await setElement('#character-name',castName.name);await setElement('#handle',castName.handle);await setElement('#character-kana',get(map,'base.nameKana'));await setElement('#player-name',get(map,'base.player'));await setElement('#affiliation',get(map,'base.post'));await setElement('#citizen-rank',get(map,'base.rank'));await setElement('#summary',get(map,'base.lifepath.memo'));
const profileParts=[get(map,'base.memoir'),get(map,'base.memo')&&`【メモ】\n${get(map,'base.memo')}`,[['出身',get(map,'base.birth')],['年齢',get(map,'base.age')],['性別',get(map,'base.sex')],['身長',get(map,'base.height')],['体重',get(map,'base.weight')],['瞳',get(map,'base.eyes')],['髪',get(map,'base.hair')],['肌',get(map,'base.skin')],['経験',get(map,'base.lifepath.experience')],['環境',get(map,'base.lifepath.environment')],['邂逅',get(map,'base.lifepath.encouter')]].filter(([,value])=>value).map(([key,value])=>`${key}：${value}`).join('\n')].filter(Boolean);await setElement('#profile',profileParts.join('\n\n'));
await importStyles(data,map);await importAbilities(map);await importGeneral(map);await importStyleSkills(map);await importOutfits(map);document.dispatchEvent(new Event('input',{bubbles:true}));msg.textContent='反映しました。内容を確認し、保存ボタンでDBへ保存してください。';setTimeout(()=>dialog.close(),900)}catch(error){console.error(error);msg.textContent='取込エラー：'+error.message}finally{apply.disabled=false}});
})();
