import { supabase } from './supabase-client.js';
import { requireAuth } from './auth-state.js';
import { STYLE_DATA, UTSUWA_ATTRIBUTES } from './style-data.js';
import { SITE_BASE_PATH } from './config.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SUITS=['reason','passion','life','mundane'];
const SUIT_MARKS=['♠','♣','♥','♦'];
const FIXED_GENERAL=[['医療','reason'],['射撃','reason'],['知覚','reason'],['電脳','reason'],['心理','passion'],['自我','passion'],['交渉','passion'],['運動','life'],['回避','life'],['白兵','life'],['信用','mundane'],['圧力','mundane'],['隠密','mundane']];
const ABILITIES=[['reason','理性','REASON'],['passion','感情','PASSION'],['life','生命','LIFE'],['mundane','外界','MUNDANE']];
let user,character=null,skills=[],outfits=[],showAllGeneral=true,saveTimer,saving=false,pending=false,importMode='',loadingCharacter=false;

init();
async function init(){user=await requireAuth();if(!user)return;renderStyles();renderAbilities();bind();const id=new URLSearchParams(location.search).get('id');if(id)await loadCharacter(id);else createNewState();}
function bind(){
  document.addEventListener('input',e=>{if(e.target.matches('input,select,textarea')){handleValueInput(e.target);recalc();queueSave();}});
  document.addEventListener('change',e=>{if(e.target.matches('input,select,textarea')){handleValueInput(e.target);recalc();queueSave();}});
  document.addEventListener('click',e=>{const t=e.target.closest('.section-toggle');if(t)t.parentElement.classList.toggle('is-open');const d=e.target.closest('[data-delete-skill]');if(d){skills=skills.filter(x=>x._key!==d.dataset.deleteSkill);renderSkills();recalc();queueSave();}const o=e.target.closest('[data-delete-outfit]');if(o){outfits=outfits.filter(x=>x._key!==o.dataset.deleteOutfit);renderOutfits();recalc();queueSave();}});
  $('#save-button').onclick=()=>saveAll(true);
  $('#toggle-general').onclick=()=>{showAllGeneral=!showAllGeneral;$('#toggle-general').textContent=showAllGeneral?'取得済みのみ表示':'全技能表示';renderSkills();};
  $('#add-general').onclick=()=>{skills.push(blankSkill('general'));renderSkills();queueSave();};
  $('#add-style-skill').onclick=()=>{skills.push(blankSkill('style'));renderSkills();queueSave();};
  $('#add-outfit').onclick=()=>{outfits.push(blankOutfit());renderOutfits();queueSave();};
  $('#import-skd').onclick=()=>openImport('skd');$('#import-ofc').onclick=()=>openImport('ofc');
  $('#tsv-apply').onclick=e=>{e.preventDefault();applyImport();$('#tsv-dialog').close();};
}
function createNewState(){character={visibility:'draft'};$('#visibility').value='draft';skills=FIXED_GENERAL.map(([name,suit])=>({...blankSkill('general'),name,level:1,free_level:1,[suit]:true,skill_kind:'general'}));skills.push({...blankSkill('connection'),name:'コネ：初期取得',level:1,free_level:1,skill_kind:'proper'});skills.push({...blankSkill('social'),name:'社会：N◎VA',level:1,free_level:1,skill_kind:'proper'});skills.push({...blankSkill('social'),name:'社会：初期取得',level:2,free_level:2,skill_kind:'proper'});renderSkills();renderOutfits();recalc();setStatus('新規キャスト／未保存','saved');}
async function loadCharacter(publicId){setStatus('読込中…','saving');loadingCharacter=true;const {data,error}=await supabase.from('characters').select('*').eq('public_id',publicId).eq('owner_id',user.id).maybeSingle();if(error||!data){setStatus(error?.message||'読込失敗','error');loadingCharacter=false;return;}character=data;fillCharacter(data);const [s,o]=await Promise.all([supabase.from('character_skills').select('*').eq('character_id',data.id).order('sort_order'),supabase.from('character_outfits').select('*').eq('character_id',data.id).order('sort_order')]);skills=(s.data||[]).map(normalizeSkill);outfits=(o.data||[]).map(normalizeOutfit);loadingCharacter=false;renderSkills();renderOutfits();recalc();setStatus(`${data.public_id} を編集中`,'saved');}
function fillCharacter(d){['character_name','character_kana','handle','player_name','affiliation','citizen_rank','summary','profile','visibility'].forEach(n=>{const el=$('#'+n.replaceAll('_','-'));if(el)el.value=d[n]??'';});for(let i=1;i<=3;i++){$(`#style-${i}`).value=d[`style_${i}`]||'';$(`#style-${i}-mark`).value=d[`style_${i}_mark`]||'';const a=$(`#style-${i}-attribute`);if(a)a.value=d[`style_${i}_attribute`]||'';toggleAttribute(i);}for(const [k] of ABILITIES){const styleBase=Number(d[`${k}_style_base`]??d[`${k}_base`]??d[`${k}_value`]??0);const paid=Math.max(0,Number(d[`${k}_growth`]||0));const current=Number(d[`${k}_base`]??styleBase)+paid;setAbilityField(k,current,styleBase,paid);const cStyle=Number(d[`${k}_control_style_base`]??d[`${k}_control_base`]??d[`${k}_control`]??0);const cPaid=Math.max(0,Number(d[`${k}_control_growth`]||0));setAbilityField(`${k}-control`,Number(d[`${k}_control_base`]??cStyle)+cPaid,cStyle,cPaid);$(`#${k}-mod`).value=Number(d[`${k}_gear`]||0)+Number(d[`${k}_manual`]||0);$(`#${k}-control-mod`).value=Number(d[`${k}_control_gear`]||0)+Number(d[`${k}_control_manual`]||0);}$('#cs-base').value=d.cs_base??d.cs??0;$('#cs-mod').value=Number(d.cs_gear||0)+Number(d.cs_manual||0);updateDivines(false);}
function setAbilityField(id,current,baseline,paid){const el=$(`#${id}-base`);el.value=current;el.dataset.styleBase=baseline;el.dataset.paidGrowth=paid;}
function renderStyles(){const options='<option value="">選択</option>'+STYLE_DATA.map(x=>`<option>${esc(x.name)}</option>`).join('');const attrs='<option value="">属性を選択</option>'+UTSUWA_ATTRIBUTES.map(x=>`<option>${esc(x.name)}</option>`).join('');$('#style-grid').innerHTML=[1,2,3].map(i=>`<article class="style-card"><div class="style-fields"><label>スタイル<select id="style-${i}">${options}</select></label><label>指定<select id="style-${i}-mark"><option value="">無印</option><option>◎</option><option>●</option><option>◎●</option></select></label><label id="style-${i}-attribute-wrap" class="utsuwa-attribute" hidden>ウツワ属性<select id="style-${i}-attribute">${attrs}</select></label></div><section class="divine-field"><span>神業 <small>DIVINE WORK</small></span><ruby><strong id="divine-${i}"></strong><rt id="divine-${i}-yomi"></rt></ruby></section></article>`).join('');$('#style-grid').addEventListener('change',e=>{if(e.target.matches('[id^="style-"]')){for(let i=1;i<=3;i++)toggleAttribute(i);updateDivines(true);}});}
function toggleAttribute(i){const wrap=$(`#style-${i}-attribute-wrap`),sel=$(`#style-${i}-attribute`);if(!wrap||!sel)return;const is=$(`#style-${i}`).value==='ウツワ';wrap.hidden=!is;if(!is)sel.value='';}
function styleRecord(i){const name=$(`#style-${i}`).value;if(name==='ウツワ')return UTSUWA_ATTRIBUTES.find(x=>x.name===$(`#style-${i}-attribute`).value)||null;return STYLE_DATA.find(x=>x.name===name)||null;}
function updateDivines(applyBase=false){for(let i=1;i<=3;i++){const x=STYLE_DATA.find(s=>s.name===$(`#style-${i}`).value);$(`#divine-${i}`).textContent=x?.divine||'未選択';$(`#divine-${i}-yomi`).textContent=x?.divineYomi||x?.divine||'';}const count=[1,2,3].filter(i=>$(`#style-${i}`).value).length;$('#style-warning').textContent=count===3?'':'3枠すべてのスタイルを選択してください。';if(applyBase&&!loadingCharacter)applyStyleBaseValues();}
function applyStyleBaseValues(){const totals={reason:[0,0],passion:[0,0],life:[0,0],mundane:[0,0]};let complete=true;for(let i=1;i<=3;i++){const r=styleRecord(i);if(!r){complete=false;continue;}for(const [k] of ABILITIES){totals[k][0]+=Number(r[k]?.[0]||0);totals[k][1]+=Number(r[k]?.[1]||0);}}if(!complete){$('#style-warning').textContent='ウツワを選択した場合は属性も選択してください。';return;}for(const [k] of ABILITIES){applyNewBaseline(k,totals[k][0]);applyNewBaseline(`${k}-control`,totals[k][1]);}recalc();}
function applyNewBaseline(id,baseline){const el=$(`#${id}-base`);const oldBaseline=Number(el.dataset.styleBase||0),paid=Number(el.dataset.paidGrowth||0),current=Number(el.value||0);const wasUntouched=current===oldBaseline+paid||!current;el.dataset.styleBase=baseline;if(wasUntouched)el.value=baseline+paid;}
function renderAbilities(){$('#ability-grid').innerHTML=ABILITIES.map(([k,jp,en])=>abilityCard(k,jp,en)).join('')+csCard();}
function abilityCard(k,jp,en){return `<article class="ability-card"><h3>${jp} <small>${en}</small></h3><div class="ability-values"><label>能力値<input id="${k}-base" type="number" min="0" value="0" data-style-base="0" data-paid-growth="0"></label><label>修正<input id="${k}-mod" type="number" value="0"></label><strong id="${k}-final">0</strong></div><div class="ability-values"><label>制御値<input id="${k}-control-base" type="number" min="0" value="0" data-style-base="0" data-paid-growth="0"></label><label>修正<input id="${k}-control-mod" type="number" value="0"></label><strong id="${k}-control-final">0</strong></div></article>`;}
function csCard(){return `<article class="ability-card"><h3>CS <small>CS</small></h3><div class="ability-values"><label>基礎値<input id="cs-base" type="number" value="0"></label><label>修正<input id="cs-mod" type="number" value="0"></label><strong id="cs-final">0</strong></div></article>`;}
function handleValueInput(el){if(el.matches('[id$="-base"][data-style-base]')){const baseline=Number(el.dataset.styleBase||0),current=Number(el.value||0),previous=Number(el.dataset.paidGrowth||0);el.dataset.paidGrowth=Math.max(previous,current-baseline,0);}}
function blankSkill(category){return {_key:crypto.randomUUID(),category,name:'',level:1,free_level:0,skill_kind:category==='style'?'normal':'general',reason:false,passion:false,life:false,mundane:false,timing:'',target:'',range:'',difficulty:'',confrontation:'',description:'',sort_order:skills.length};}
function normalizeSkill(x){const n={...blankSkill(x.category),...x,_key:x.id||crypto.randomUUID(),free_level:Number(x.free_level||0),skill_kind:x.skill_kind||inferSkillKind(x)};if(n.name==='初期取得')n.name=n.category==='connection'?'コネ：初期取得':n.category==='social'?'社会：初期取得':n.name;return n;}
function inferSkillKind(x){if(x.category==='style')return /奥義/.test(x.type||'')?'ultimate':/秘技/.test(x.type||'')?'secret':'normal';return String(x.name||'').includes('：')?'proper':'general';}
function renderSkills(){const all=showAllGeneral?mergeGeneralMaster(skills):skills.filter(x=>x.category!=='general'||Number(x.level)>0);$('#general-skills').innerHTML=[skillTable('一般技能','GENERAL SKILLS',all.filter(x=>x.category==='general'),false),skillTable('社会','SOCIAL',all.filter(x=>x.category==='social'),false),skillTable('コネクション','CONNECTIONS',all.filter(x=>x.category==='connection'),false)].join('');$('#style-skills').innerHTML=skillTable('スタイル技能','STYLE SKILLS',skills.filter(x=>x.category==='style'),true);bindSkillRows();}
function mergeGeneralMaster(list){const out=[...list];for(const [name] of FIXED_GENERAL)if(!out.some(x=>x.category==='general'&&x.name===name))out.push({...blankSkill('general'),name,level:0});return out;}
function skillTable(jp,en,rows,detail){if(!rows.length)return'';return `<section class="skill-group"><h3 class="skill-group-title">${jp} <small>${en}</small></h3><table class="skill-table ${detail?'has-detail':'no-detail'}"><thead><tr><th class="name-col">名称</th><th class="type-col">種別</th><th class="lv-col">LV</th>${SUIT_MARKS.map(x=>`<th class="suit-col">${x}</th>`).join('')}${detail?'<th>詳細</th>':''}<th></th></tr></thead><tbody>${rows.map(x=>skillRow(x,detail)).join('')}</tbody></table></section>`;}
function skillRow(x,detail){return `<tr data-skill-key="${x._key}"><td><input data-f="name" value="${esc(x.name)}"></td><td><select data-f="skill_kind">${['general','proper','normal','secret','ultimate'].map(v=>`<option value="${v}" ${x.skill_kind===v?'selected':''}>${{general:'一般',proper:'固有名詞',normal:'通常',secret:'秘技',ultimate:'奥義'}[v]}</option>`).join('')}</select></td><td><input data-f="level" type="number" min="0" value="${x.level||0}"></td>${SUITS.map((s,idx)=>`<td class="suit-cell"><label class="suit-check"><input data-f="${s}" type="checkbox" ${x[s]?'checked':''}><span>${SUIT_MARKS[idx]}</span></label></td>`).join('')}${detail?`<td><input data-f="description" value="${esc(x.description||x.timing||'')}"></td>`:''}<td><button class="row-delete" data-delete-skill="${x._key}" type="button">×</button></td></tr>`;}
function bindSkillRows(){$$('[data-skill-key]').forEach(tr=>tr.querySelectorAll('[data-f]').forEach(el=>el.oninput=()=>{let x=skills.find(s=>s._key===tr.dataset.skillKey);if(!x){x=mergeGeneralMaster(skills).find(s=>s._key===tr.dataset.skillKey);if(x)skills.push(x);}if(!x)return;const f=el.dataset.f;x[f]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(SUITS.includes(f)){x.level=SUITS.filter(s=>x[s]).length;renderSkills();}else if(f==='level'){const lv=Math.max(0,Number(el.value||0));x.level=lv;SUITS.forEach((s,i)=>x[s]=i<Math.min(4,lv));renderSkills();}recalc();queueSave();}));}
function blankOutfit(){return {_key:crypto.randomUUID(),category:'other',name:'',purchase_value:'',experience_cost:0,concealment:'',attack:'',defense:'',range:'',slot:'',control_modifier:0,cs_modifier:0,mundane_modifier:0,description:'',sort_order:outfits.length};}
function normalizeOutfit(x){return {...blankOutfit(),...x,_key:x.id||crypto.randomUUID(),experience_cost:Number(x.experience_cost||0)};}
function renderOutfits(){$('#outfit-list').innerHTML=outfits.map(x=>`<article class="outfit-card" data-outfit-key="${x._key}"><label>分類<select data-o="category">${['weapon','armor','cyberware','tron','vehicle','residence','other'].map(v=>`<option value="${v}" ${x.category===v?'selected':''}>${{weapon:'武器',armor:'防具',cyberware:'サイバーウェア',tron:'トロン',vehicle:'ヴィークル',residence:'住居',other:'その他'}[v]}</option>`).join('')}</select></label><label>名称<input data-o="name" value="${esc(x.name)}"></label><label>購入<input data-o="purchase_value" value="${esc(x.purchase_value)}"></label><label>常備化<input data-o="experience_cost" type="number" value="${x.experience_cost}"></label><label>部位<input data-o="slot" value="${esc(x.slot)}"></label><label>解説<input data-o="description" value="${esc(x.description)}"></label><button class="row-delete" data-delete-outfit="${x._key}" type="button">×</button></article>`).join('')||'<p>アウトフィット未登録</p>';$$('[data-outfit-key]').forEach(card=>card.querySelectorAll('[data-o]').forEach(el=>el.oninput=()=>{const x=outfits.find(o=>o._key===card.dataset.outfitKey);x[el.dataset.o]=el.type==='number'?Number(el.value):el.value;recalc();queueSave();}));}
function finalValue(k){return Number($(`#${k}-base`)?.value||0)+Number($(`#${k}-mod`)?.value||0);}
function finalControl(k){return Number($(`#${k}-control-base`)?.value||0)+Number($(`#${k}-control-mod`)?.value||0);}
function recalc(){for(const [k] of ABILITIES){$(`#${k}-final`).textContent=finalValue(k);$(`#${k}-control-final`).textContent=finalControl(k);}$('#cs-final').textContent=Number($('#cs-base').value||0)+Number($('#cs-mod').value||0);const exp=calculateExp();$('#exp-total').textContent=exp.total;$('#exp-breakdown').innerHTML=Object.entries(exp.parts).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');}
function calculateExp(){let ability=0,control=0,general=0,style=0,outfit=0;for(const [k] of ABILITIES){const base=$(`#${k}-base`),growth=Number(base.dataset.paidGrowth||0),styleBase=Number(base.dataset.styleBase||0);for(let i=1;i<=growth;i++)ability+=(styleBase+i)<=10?20:40;const cb=$(`#${k}-control-base`),cg=Number(cb.dataset.paidGrowth||0),cStyle=Number(cb.dataset.styleBase||0);for(let i=1;i<=cg;i++)control+=(cStyle+i)<=16?20:40;}for(const s of skills){const paid=Math.max(0,Number(s.level||0)-Number(s.free_level||0));if(s.category==='style')style+=paid*({normal:10,secret:20,ultimate:50}[s.skill_kind]||10);else general+=paid*(s.skill_kind==='proper'?5:10);}const mundane=finalValue('mundane');for(const o of outfits){const p=Number(o.experience_cost||0);if(p>mundane)outfit+=p;}return {total:ability+control+general+style+outfit,parts:{能力値:ability,制御値:control,一般技能:general,スタイル技能:style,アウトフィット:outfit}};}
function openImport(mode){importMode=mode;$('#tsv-title').textContent=`${mode.toUpperCase()} TSV取込`;$('#tsv-text').value='';$('#tsv-dialog').showModal();}
function parseTSV(t){const lines=String(t).replace(/\r/g,'').trim().split('\n').filter(Boolean).map(x=>x.split('\t'));if(!lines.length)return[];const h=lines.shift().map(x=>x.trim());return lines.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||'').replace(/\\n/g,'\n')])));}
function applyImport(){const rows=parseTSV($('#tsv-text').value);if(importMode==='skd'){for(const r of rows)skills.push({...blankSkill('style'),name:r['名称']||'',skill_kind:/奥義/.test(r['種別']||'')?'ultimate':/秘技/.test(r['種別']||'')?'secret':'normal',level:Number(r['レベル']||1),timing:r['タイミング']||'',target:r['対象']||'',range:r['射程']||'',difficulty:r['目標値']||'',confrontation:r['対決']||'',description:r['解説']||''});renderSkills();}else{for(const r of rows){const map={weapons:'weapon',armours:'armor',vehicles:'vehicle',residences:'residence',outfits:'other',武器:'weapon',防具:'armor',ヴィークル:'vehicle',住居:'residence',住宅:'residence',装備:'other'};outfits.push({...blankOutfit(),category:map[r.target]||'other',name:r.name||'',purchase_value:r.purchase||'',experience_cost:Number(r.permanent||0),concealment:[r.concealA,r.concealB].filter(Boolean).join('/'),attack:r.attack||'',defense:r.defense||'',range:r.range||'',slot:r.part||r.slot||'',description:r.notes||''});}renderOutfits();}recalc();queueSave();}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveAll(false),700);}
function collectCharacter(){const p={owner_id:user.id,character_name:$('#character-name').value.trim(),character_kana:$('#character-kana').value.trim(),handle:$('#handle').value.trim(),player_name:$('#player-name').value.trim(),affiliation:$('#affiliation').value.trim(),citizen_rank:$('#citizen-rank').value.trim(),summary:$('#summary').value,profile:$('#profile').value,visibility:$('#visibility').value,experience_points:Number($('#exp-total').textContent||0)};for(let i=1;i<=3;i++){const x=STYLE_DATA.find(s=>s.name===$(`#style-${i}`).value);p[`style_${i}`]=$(`#style-${i}`).value;p[`style_${i}_mark`]=$(`#style-${i}-mark`).value;p[`style_${i}_attribute`]=$(`#style-${i}-attribute`)?.value||'';p[`divine_${i}`]=x?.divine||'';p[`divine_${i}_yomi`]=x?.divineYomi||x?.divine||'';}for(const [k] of ABILITIES){const b=$(`#${k}-base`),cb=$(`#${k}-control-base`);p[`${k}_style_base`]=Number(b.dataset.styleBase||0);p[`${k}_base`]=Number(b.value||0)-Number(b.dataset.paidGrowth||0);p[`${k}_growth`]=Number(b.dataset.paidGrowth||0);p[`${k}_gear`]=Number($(`#${k}-mod`).value||0);p[`${k}_manual`]=0;p[`${k}_value`]=finalValue(k);p[`${k}_control_style_base`]=Number(cb.dataset.styleBase||0);p[`${k}_control_base`]=Number(cb.value||0)-Number(cb.dataset.paidGrowth||0);p[`${k}_control_growth`]=Number(cb.dataset.paidGrowth||0);p[`${k}_control_gear`]=Number($(`#${k}-control-mod`).value||0);p[`${k}_control_manual`]=0;p[`${k}_control`]=finalControl(k);}p.cs_base=Number($('#cs-base').value||0);p.cs_gear=Number($('#cs-mod').value||0);p.cs_manual=0;p.cs=p.cs_base+p.cs_gear;return p;}
async function writeCharacter(payload){let q=character?.id?supabase.from('characters').update(payload).eq('id',character.id).eq('owner_id',user.id):supabase.from('characters').insert(payload);let result=await q.select('*').single();if(result.error&&String(result.error.message).includes('style_1_attribute')){const clean={...payload};for(let i=1;i<=3;i++)delete clean[`style_${i}_attribute`];q=character?.id?supabase.from('characters').update(clean).eq('id',character.id).eq('owner_id',user.id):supabase.from('characters').insert(clean);result=await q.select('*').single();}return result;}
async function saveAll(force){if(saving){pending=true;return;}if(!$('#character-name').value.trim()||!$('#player-name').value.trim()){if(force)setStatus('キャスト名とプレイヤー名は必須です','error');return;}saving=true;setStatus('保存中…','saving');try{const result=await writeCharacter(collectCharacter());if(result.error)throw result.error;character=result.data;const ds=await supabase.from('character_skills').delete().eq('character_id',character.id);if(ds.error)throw ds.error;const dof=await supabase.from('character_outfits').delete().eq('character_id',character.id);if(dof.error)throw dof.error;const skillRows=skills.filter(x=>Number(x.level)>0&&x.name.trim()).map((x,i)=>({character_id:character.id,category:x.category,name:x.name,level:Number(x.level||0),free_level:Number(x.free_level||0),skill_kind:x.skill_kind,reason:!!x.reason,passion:!!x.passion,life:!!x.life,mundane:!!x.mundane,timing:x.timing||'',target:x.target||'',range:x.range||'',difficulty:x.difficulty||'',confrontation:x.confrontation||'',description:x.description||'',sort_order:i}));if(skillRows.length){const r=await supabase.from('character_skills').insert(skillRows);if(r.error)throw r.error;}const outfitRows=outfits.filter(x=>x.name.trim()).map((x,i)=>({character_id:character.id,category:x.category,name:x.name,purchase_value:x.purchase_value||'',experience_cost:Number(x.experience_cost||0),concealment:x.concealment||'',attack:x.attack||'',defense:x.defense||'',range:x.range||'',slot:x.slot||'',description:x.description||'',control_modifier:Number(x.control_modifier||0),cs_modifier:Number(x.cs_modifier||0),mundane_modifier:Number(x.mundane_modifier||0),sort_order:i}));if(outfitRows.length){const r=await supabase.from('character_outfits').insert(outfitRows);if(r.error)throw r.error;}history.replaceState(null,'',`${SITE_BASE_PATH}sheet.html?id=${encodeURIComponent(character.public_id)}`);setStatus('保存完了','saved');window.dispatchEvent(new CustomEvent('tnx-sheet-saved'));}catch(e){console.error(e);setStatus(e.message||'保存失敗','error');}finally{saving=false;if(pending){pending=false;saveAll(false);}}}
function setStatus(text,cls=''){$('#save-status').textContent=text;$('#save-status').className=cls;}
