import { supabase } from "./supabase-client.js";
import { requireAuth } from "./auth-state.js";
import { STYLE_DATA, UTSUWA_ATTRIBUTES } from "./style-data.js";
import { SITE_BASE_PATH } from "./config.js";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const SUITS=["reason","passion","life","mundane"], MARKS=["♠","♣","♥","♦"];
const ABILITIES=[["reason","理性","REASON"],["passion","感情","PASSION"],["life","生命","LIFE"],["mundane","外界","MUNDANE"]];
const GENERAL_MASTER=[
  ["医療","reason","general"],["射撃","reason","general"],["知覚","reason","general"],["電脳","reason","general"],["製作：","reason","proper"],
  ["心理","passion","general"],["自我","passion","general"],["交渉","passion","general"],["芸術：","passion","proper"],
  ["運動","life","general"],["回避","life","general"],["白兵","life","general"],["操縦：","life","proper"],
  ["信用","mundane","general"],["圧力","mundane","general"],["隠密","mundane","general"]
];
const OUTFIT_LABELS={weapon:"武器",armor:"防具",cyberware:"サイバーウェア",tron:"トロン",vehicle:"ヴィークル",residence:"住居",other:"その他"};
let user,character=null,skills=[],outfits=[],loading=false,dirty=false,saving=false,pending=false,saveTimer,importMode="";
const styleBaseline={};

init();
async function init(){user=await requireAuth();if(!user)return;renderStyles();renderAbilities();bind();const id=new URLSearchParams(location.search).get("id");if(id)await loadCharacter(id);else createNew();}
function bind(){
  document.addEventListener("input",onEdit);document.addEventListener("change",onEdit);
  document.addEventListener("click",e=>{const t=e.target.closest(".section-toggle");if(t){t.closest(".sheet-section")?.classList.toggle("is-open");return;}const sd=e.target.closest("[data-delete-skill]");if(sd){skills=skills.filter(x=>x._key!==sd.dataset.deleteSkill);renderSkills();recalc();markDirty();}const od=e.target.closest("[data-delete-outfit]");if(od){outfits=outfits.filter(x=>x._key!==od.dataset.deleteOutfit);renderOutfits();recalc();markDirty();}});
  $("#save-button").onclick=()=>saveAll(true);
  $("#add-general").onclick=()=>addSkill("general","proper");
  $("#add-social").onclick=()=>addSkill("social","proper");
  $("#add-connection").onclick=()=>addSkill("connection","proper");
  $("#add-style-skill").onclick=()=>addSkill("style","normal");
  $("#add-outfit").onclick=()=>{outfits.push(blankOutfit());renderOutfits();markDirty();};
  $("#import-skd").onclick=()=>openImport("skd");$("#import-ofc").onclick=()=>openImport("ofc");
  $("#tsv-apply").onclick=e=>{e.preventDefault();applyImport();$("#tsv-dialog").close();};
}
function onEdit(e){if(loading||!e.target.matches("input,select,textarea"))return;recalc();markDirty();}
function addSkill(category,kind){skills.push({...blankSkill(category),skill_kind:kind});renderSkills();markDirty();}
function createNew(){loading=true;character={visibility:"private"};$("#visibility").value="private";skills=GENERAL_MASTER.filter(x=>x[2]==="general").map(([name,suit])=>({...blankSkill("general"),name,level:1,free_level:1,[suit]:true,skill_kind:"general"}));skills.push({...blankSkill("social"),name:"社会：N◎VA",level:1,free_level:1,skill_kind:"proper"},{...blankSkill("social"),name:"社会：初期取得",level:1,free_level:1,skill_kind:"proper"},{...blankSkill("connection"),name:"コネ：初期取得",level:1,free_level:1,skill_kind:"proper"},{...blankSkill("connection"),name:"コネ：初期取得",level:1,free_level:1,skill_kind:"proper"});renderSkills();renderOutfits();recalc();loading=false;dirty=true;setStatus("未保存","unsaved");}
async function loadCharacter(publicId){loading=true;setStatus("読込中…","saving");const {data,error}=await supabase.from("characters").select("*").eq("public_id",publicId).eq("owner_id",user.id).maybeSingle();if(error||!data){setStatus(jpError(error?.message||"キャストを読み込めませんでした。"),"error");loading=false;return;}character=data;fillCharacter(data);const [s,o]=await Promise.all([supabase.from("character_skills").select("*").eq("character_id",data.id).order("sort_order"),supabase.from("character_outfits").select("*").eq("character_id",data.id).order("sort_order")]);skills=(s.data||[]).map(normalizeSkill);outfits=(o.data||[]).map(normalizeOutfit);renderSkills();renderOutfits();recalc();loading=false;dirty=false;setStatus("保存済み","saved");}
function fillCharacter(d){["character_name","character_kana","handle","player_name","affiliation","citizen_rank","summary","profile"].forEach(n=>{const el=$("#"+n.replaceAll("_","-"));if(el)el.value=d[n]??"";});$("#visibility").value=d.visibility==="public"?"public":"private";for(let i=1;i<=3;i++){$(`#style-${i}`).value=d[`style_${i}`]||"";$(`#style-${i}-mark`).value=d[`style_${i}_mark`]||"";const a=$(`#style-${i}-attribute`);if(a)a.value=d[`style_${i}_attribute`]||"";toggleAttribute(i);}calculateBaselines();for(const [k] of ABILITIES){$(`#${k}-base`).value=Number(d[`${k}_base`]??d[`${k}_value`]??styleBaseline[k]??0);$(`#${k}-mod`).value=Number(d[`${k}_gear`]||0)+Number(d[`${k}_manual`]||0);const ck=`${k}-control`;$(`#${ck}-base`).value=Number(d[`${k}_control_base`]??d[`${k}_control`]??styleBaseline[ck]??0);$(`#${ck}-mod`).value=Number(d[`${k}_control_gear`]||0)+Number(d[`${k}_control_manual`]||0);}$("#cs-base").value=d.cs_base??d.cs??0;$("#cs-mod").value=Number(d.cs_gear||0)+Number(d.cs_manual||0);updateDivines(false);}

function renderStyles(){const opts='<option value="">選択</option>'+STYLE_DATA.map(x=>`<option>${esc(x.name)}</option>`).join("");const attrs='<option value="">属性を選択</option>'+UTSUWA_ATTRIBUTES.map(x=>`<option>${esc(x.name)}</option>`).join("");$("#style-grid").innerHTML=[1,2,3].map(i=>`<article class="style-card"><div class="style-fields"><label>スタイル<select id="style-${i}">${opts}</select></label><label>指定<select id="style-${i}-mark"><option value="">無印</option><option>◎</option><option>●</option><option>◎●</option></select></label><label id="style-${i}-attribute-wrap" hidden>ウツワ属性<select id="style-${i}-attribute">${attrs}</select></label></div><section class="divine-field"><ruby><strong id="divine-${i}">未選択</strong><rt id="divine-${i}-yomi"></rt></ruby><span>神業</span></section></article>`).join("");$("#style-grid").addEventListener("change",e=>{if(!e.target.matches('[id^="style-"]'))return;for(let i=1;i<=3;i++)toggleAttribute(i);updateDivines(true);});}
function toggleAttribute(i){const w=$(`#style-${i}-attribute-wrap`),s=$(`#style-${i}-attribute`);if(!w||!s)return;const yes=$(`#style-${i}`).value==="ウツワ";w.hidden=!yes;if(!yes)s.value="";}
function styleRecord(i){const n=$(`#style-${i}`).value;return n==="ウツワ"?UTSUWA_ATTRIBUTES.find(x=>x.name===$(`#style-${i}-attribute`).value)||null:STYLE_DATA.find(x=>x.name===n)||null;}
function calculateBaselines(){for(const [k] of ABILITIES){styleBaseline[k]=0;styleBaseline[`${k}-control`]=0;}for(let i=1;i<=3;i++){const r=styleRecord(i);if(!r)continue;for(const [k] of ABILITIES){styleBaseline[k]+=Number(r[k]?.[0]||0);styleBaseline[`${k}-control`]+=Number(r[k]?.[1]||0);}}}
function updateDivines(apply){for(let i=1;i<=3;i++){const x=STYLE_DATA.find(s=>s.name===$(`#style-${i}`).value);$(`#divine-${i}`).textContent=x?.divine||"未選択";$(`#divine-${i}-yomi`).textContent=x?.divineYomi||x?.divine||"";}$("#style-warning").textContent=[1,2,3].filter(i=>$(`#style-${i}`).value).length===3?"":"3枠すべてのスタイルを選択してください。";if(!apply||loading)return;const old={...styleBaseline};calculateBaselines();for(const [k] of ABILITIES){adjustBaseline(k,old[k]||0,styleBaseline[k]||0);adjustBaseline(`${k}-control`,old[`${k}-control`]||0,styleBaseline[`${k}-control`]||0);}recalc();}
function adjustBaseline(id,oldBase,newBase){const el=$(`#${id}-base`);if(el&&(Number(el.value||0)===oldBase||Number(el.value||0)===0))el.value=newBase;}
function renderAbilities(){$("#ability-grid").innerHTML=ABILITIES.map(([k,jp,en])=>`<article class="ability-card ability-matrix"><h3>${jp} <small>${en}</small></h3><div class="ability-matrix__header"><span></span><strong>能力値</strong><strong>制御値</strong></div><div class="ability-matrix__row"><span>現在値</span><input id="${k}-base" type="number" min="0" value="0"><input id="${k}-control-base" type="number" min="0" value="0"></div><div class="ability-matrix__row"><span>補正値</span><input id="${k}-mod" type="number" value="0"><input id="${k}-control-mod" type="number" value="0"></div><div class="ability-matrix__row ability-matrix__result"><span>最終値</span><strong id="${k}-final">0</strong><strong id="${k}-control-final">0</strong></div></article>`).join("")+`<article class="ability-card ability-card--cs"><h3>CS</h3><div class="cs-row"><label>現在値<input id="cs-base" type="number" value="0"></label><label>補正値<input id="cs-mod" type="number" value="0"></label><strong id="cs-final">0</strong></div></article>`;}

function blankSkill(category){return {_key:crypto.randomUUID(),category,name:"",level:1,free_level:0,skill_kind:category==="style"?"normal":"proper",reason:false,passion:false,life:false,mundane:false,timing:"",target:"",range:"",difficulty:"",confrontation:"",description:"",sort_order:skills.length};}
function normalizeSkill(x){const n={...blankSkill(x.category),...x,_key:x.id||crypto.randomUUID(),free_level:Number(x.free_level||0),skill_kind:x.skill_kind||inferKind(x)};if(n.name==="初期取得")n.name=n.category==="connection"?"コネ：初期取得":"社会：初期取得";return n;}
function inferKind(x){if(x.category==="style")return /奥義/.test(x.type||"")?"ultimate":/秘技/.test(x.type||"")?"secret":"normal";return String(x.name||"").includes("：")?"proper":"general";}
function mergedGeneral(){const out=[...skills.filter(x=>x.category==="general")];for(const [name,suit,kind] of GENERAL_MASTER)if(!out.some(x=>x.name===name))out.push({...blankSkill("general"),name,level:0,skill_kind:kind,[suit]:false,_master:true});return out.sort((a,b)=>GENERAL_MASTER.findIndex(x=>x[0]===a.name)-GENERAL_MASTER.findIndex(x=>x[0]===b.name));}
function renderSkills(){$("#general-skills").innerHTML=[skillTable("一般技能","GENERAL SKILLS",mergedGeneral(),false),skillTable("社会","SOCIAL",skills.filter(x=>x.category==="social"),false),skillTable("コネクション","CONNECTIONS",skills.filter(x=>x.category==="connection"),false)].join("");$("#style-skills").innerHTML=skillTable("スタイル技能","STYLE SKILLS",skills.filter(x=>x.category==="style"),true);bindSkillRows();}
function skillTable(jp,en,rows,detail){if(!rows.length)return"";return `<section class="skill-group"><h3 class="skill-group-title">${jp} <small>${en}</small></h3><table class="skill-table ${detail?"has-detail":"no-detail"}"><thead><tr><th class="name-col">名称</th><th class="type-col">種別</th><th class="lv-col">LV</th>${MARKS.map(m=>`<th class="suit-col">${m}</th>`).join("")}${detail?"<th>詳細</th>":""}<th></th></tr></thead><tbody>${rows.map(x=>skillRow(x,detail)).join("")}</tbody></table></section>`;}
function skillRow(x,detail){const kinds=x.category==="style"?["normal","secret","ultimate"]:["proper"],labels={proper:"固有名詞",normal:"通常",secret:"秘技",ultimate:"奥義"};return `<tr data-skill-key="${x._key}"><td><input data-f="name" value="${esc(x.name)}"></td><td><select data-f="skill_kind">${kinds.map(v=>`<option value="${v}" ${x.skill_kind===v?"selected":""}>${labels[v]}</option>`).join("")}</select></td><td><input data-f="level" type="number" min="0" value="${Number(x.level)||0}"></td>${SUITS.map((s,i)=>`<td class="suit-cell"><label class="suit-check"><input data-f="${s}" type="checkbox" ${x[s]?"checked":""}><span>${MARKS[i]}</span></label></td>`).join("")}${detail?`<td><textarea data-f="description" rows="2">${esc(x.description||x.timing||"")}</textarea></td>`:""}<td><button class="row-delete" data-delete-skill="${x._key}" type="button">×</button></td></tr>`;}
function bindSkillRows(){$$('[data-skill-key]').forEach(tr=>tr.querySelectorAll('[data-f]').forEach(el=>el.oninput=()=>{let x=skills.find(s=>s._key===tr.dataset.skillKey);if(!x){x=mergedGeneral().find(s=>s._key===tr.dataset.skillKey);if(x)skills.push(x);}if(!x)return;const f=el.dataset.f;x[f]=el.type==="checkbox"?el.checked:el.type==="number"?Number(el.value):el.value;if(SUITS.includes(f)){x.level=SUITS.filter(s=>x[s]).length;renderSkills();}else if(f==="level"){const lv=Math.max(0,Number(el.value||0));x.level=lv;SUITS.forEach((s,i)=>x[s]=i<Math.min(lv,4));renderSkills();}recalc();markDirty();}));}

function blankOutfit(){return {_key:crypto.randomUUID(),category:"other",name:"",purchase_value:"",experience_cost:0,concealment:"",attack:"",defense:"",range:"",slot:"",control_modifier:0,cs_modifier:0,mundane_modifier:0,description:"",sort_order:outfits.length};}
function normalizeOutfit(x){return {...blankOutfit(),...x,_key:x.id||crypto.randomUUID(),experience_cost:Number(x.experience_cost||0)};}
function outfitFields(o){const common=`<label>名称<input data-o="name" value="${esc(o.name)}"></label><label>購入<input data-o="purchase_value" value="${esc(o.purchase_value)}"></label><label>常備化<input data-o="experience_cost" type="number" value="${o.experience_cost}"></label>`;const desc=`<label class="outfit-wide">解説<textarea data-o="description" rows="2">${esc(o.description)}</textarea></label>`;if(o.category==="weapon")return common+`<label>隠匿<input data-o="concealment" value="${esc(o.concealment)}"></label><label>攻撃<input data-o="attack" value="${esc(o.attack)}"></label><label>射程<input data-o="range" value="${esc(o.range)}"></label><label>部位<input data-o="slot" value="${esc(o.slot)}"></label>`+desc;if(o.category==="armor")return common+`<label>隠匿<input data-o="concealment" value="${esc(o.concealment)}"></label><label>防御<input data-o="defense" value="${esc(o.defense)}"></label><label>部位<input data-o="slot" value="${esc(o.slot)}"></label>`+desc;if(o.category==="vehicle")return common+`<label>攻撃<input data-o="attack" value="${esc(o.attack)}"></label><label>防御<input data-o="defense" value="${esc(o.defense)}"></label><label>制御修正<input data-o="control_modifier" type="number" value="${o.control_modifier}"></label><label>CS修正<input data-o="cs_modifier" type="number" value="${o.cs_modifier}"></label>`+desc;if(o.category==="residence")return common+`<label>外界修正<input data-o="mundane_modifier" type="number" value="${o.mundane_modifier}"></label><label>部位／エリア<input data-o="slot" value="${esc(o.slot)}"></label>`+desc;return common+`<label>隠匿<input data-o="concealment" value="${esc(o.concealment)}"></label><label>部位<input data-o="slot" value="${esc(o.slot)}"></label><label>制御修正<input data-o="control_modifier" type="number" value="${o.control_modifier}"></label><label>CS修正<input data-o="cs_modifier" type="number" value="${o.cs_modifier}"></label><label>外界修正<input data-o="mundane_modifier" type="number" value="${o.mundane_modifier}"></label>`+desc;}
function renderOutfits(){$("#outfit-list").innerHTML=outfits.map(o=>`<article class="outfit-card outfit-form" data-outfit-key="${o._key}"><header><label>分類<select data-o="category">${Object.entries(OUTFIT_LABELS).map(([v,l])=>`<option value="${v}" ${o.category===v?"selected":""}>${l}</option>`).join("")}</select></label><button class="row-delete" data-delete-outfit="${o._key}" type="button">×</button></header><div class="outfit-fields">${outfitFields(o)}</div></article>`).join("")||"<p>アウトフィット未登録</p>";$$('[data-outfit-key]').forEach(card=>card.querySelectorAll('[data-o]').forEach(el=>el.oninput=()=>{const o=outfits.find(x=>x._key===card.dataset.outfitKey);o[el.dataset.o]=el.type==="number"?Number(el.value):el.value;if(el.dataset.o==="category")renderOutfits();recalc();markDirty();}));}

function current(id){return Number($(`#${id}-base`)?.value||0)}function final(id){return current(id)+Number($(`#${id}-mod`)?.value||0)}
function recalc(){for(const [k] of ABILITIES){$(`#${k}-final`).textContent=final(k);$(`#${k}-control-final`).textContent=final(`${k}-control`);}$("#cs-final").textContent=Number($("#cs-base").value||0)+Number($("#cs-mod").value||0);const e=calcExp(),t=$("#exp-total"),old=Number(t.textContent||0);t.textContent=e.total;if(old!==e.total){t.classList.remove("flash");void t.offsetWidth;t.classList.add("flash");}$("#exp-breakdown").innerHTML=Object.entries(e.parts).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join("");}
function calcExp(){let ability=0,control=0,general=0,style=0,outfit=0;for(const [k] of ABILITIES){const b=Number(styleBaseline[k]||0),g=Math.max(0,current(k)-b);for(let i=1;i<=g;i++)ability+=b+i<=10?20:40;const ck=`${k}-control`,cb=Number(styleBaseline[ck]||0),cg=Math.max(0,current(ck)-cb);for(let i=1;i<=cg;i++)control+=cb+i<=16?20:40;}for(const s of skills){const p=Math.max(0,Number(s.level||0)-Number(s.free_level||0));if(s.category==="style")style+=p*({normal:10,secret:20,ultimate:50}[s.skill_kind]||10);else general+=p*5;}const mundane=final("mundane");for(const o of outfits){const p=Number(o.experience_cost||0);if(p>mundane)outfit+=p;}return {total:ability+control+general+style+outfit,parts:{能力値:ability,制御値:control,一般技能:general,スタイル技能:style,アウトフィット:outfit}};}
function markDirty(){if(loading)return;dirty=true;setStatus("未保存","unsaved");clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveAll(false),1200);}
function collect(includeAttr=true){const p={owner_id:user.id,character_name:$("#character-name").value.trim(),character_kana:$("#character-kana").value.trim(),handle:$("#handle").value.trim(),player_name:$("#player-name").value.trim(),affiliation:$("#affiliation").value.trim(),citizen_rank:$("#citizen-rank").value.trim(),summary:$("#summary").value,profile:$("#profile").value,visibility:$("#visibility").value,experience_points:Number($("#exp-total").textContent||0)};for(let i=1;i<=3;i++){const s=STYLE_DATA.find(x=>x.name===$(`#style-${i}`).value);p[`style_${i}`]=$(`#style-${i}`).value;p[`style_${i}_mark`]=$(`#style-${i}-mark`).value;if(includeAttr)p[`style_${i}_attribute`]=$(`#style-${i}-attribute`)?.value||"";p[`divine_${i}`]=s?.divine||"";p[`divine_${i}_yomi`]=s?.divineYomi||s?.divine||"";}for(const [k] of ABILITIES){p[`${k}_base`]=current(k);p[`${k}_growth`]=Math.max(0,current(k)-Number(styleBaseline[k]||0));p[`${k}_gear`]=Number($(`#${k}-mod`).value||0);p[`${k}_manual`]=0;p[`${k}_value`]=final(k);const ck=`${k}-control`;p[`${k}_control_base`]=current(ck);p[`${k}_control_growth`]=Math.max(0,current(ck)-Number(styleBaseline[ck]||0));p[`${k}_control_gear`]=Number($(`#${ck}-mod`).value||0);p[`${k}_control_manual`]=0;p[`${k}_control`]=final(ck);}p.cs_base=Number($("#cs-base").value||0);p.cs_gear=Number($("#cs-mod").value||0);p.cs_manual=0;p.cs=p.cs_base+p.cs_gear;return p;}
async function saveCharacter(p){return character?.id?supabase.from("characters").update(p).eq("id",character.id).eq("owner_id",user.id).select("*").single():supabase.from("characters").insert(p).select("*").single();}
async function saveAll(force){if(saving){pending=true;return;}if(!dirty&&force){setStatus("保存済み","saved");pulse("saved");return;}if(!$("#character-name").value.trim()||!$("#player-name").value.trim()){if(force)setStatus("キャスト名とプレイヤー名を入力してください。","error");return;}saving=true;setStatus("保存中…","saving");pulse("saving");try{let r=await saveCharacter(collect(true));if(r.error&&/style_[123]_attribute|schema cache/i.test(r.error.message||""))r=await saveCharacter(collect(false));if(r.error)throw r.error;character=r.data;let op=await supabase.from("character_skills").delete().eq("character_id",character.id);if(op.error)throw op.error;op=await supabase.from("character_outfits").delete().eq("character_id",character.id);if(op.error)throw op.error;const sr=skills.filter(x=>Number(x.level)>0&&x.name.trim()).map((x,i)=>({character_id:character.id,category:x.category,name:x.name,level:Number(x.level||0),free_level:Number(x.free_level||0),skill_kind:x.skill_kind,reason:!!x.reason,passion:!!x.passion,life:!!x.life,mundane:!!x.mundane,timing:x.timing||"",target:x.target||"",range:x.range||"",difficulty:x.difficulty||"",confrontation:x.confrontation||"",description:x.description||"",sort_order:i}));if(sr.length){op=await supabase.from("character_skills").insert(sr);if(op.error)throw op.error;}const or=outfits.filter(x=>x.name.trim()).map((x,i)=>({character_id:character.id,category:x.category,name:x.name,purchase_value:x.purchase_value||"",experience_cost:Number(x.experience_cost||0),concealment:x.concealment||"",attack:x.attack||"",defense:x.defense||"",range:x.range||"",slot:x.slot||"",description:x.description||"",control_modifier:Number(x.control_modifier||0),cs_modifier:Number(x.cs_modifier||0),mundane_modifier:Number(x.mundane_modifier||0),sort_order:i}));if(or.length){op=await supabase.from("character_outfits").insert(or);if(op.error)throw op.error;}history.replaceState(null,"",`${SITE_BASE_PATH}sheet.html?id=${encodeURIComponent(character.public_id)}`);dirty=false;setStatus("保存済み","saved");pulse("saved");}catch(e){console.error(e);dirty=true;setStatus(jpError(e.message),"error");pulse("error");}finally{saving=false;if(pending){pending=false;saveAll(false);}}}
function openImport(mode){importMode=mode;$("#tsv-title").textContent=`${mode.toUpperCase()} TSV取込`;$("#tsv-text").value="";$("#tsv-dialog").showModal();}
function parseTSV(t){const l=String(t).replace(/\r/g,"").trim().split("\n").filter(Boolean).map(x=>x.split("\t"));if(!l.length)return[];const h=l.shift().map(x=>x.trim());return l.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||"").replace(/\\n/g,"\n")])));}
function applyImport(){const rows=parseTSV($("#tsv-text").value);if(importMode==="skd"){for(const r of rows)skills.push({...blankSkill("style"),name:r["名称"]||"",skill_kind:/奥義/.test(r["種別"]||"")?"ultimate":/秘技/.test(r["種別"]||"")?"secret":"normal",level:Number(r["レベル"]||1),description:r["解説"]||""});renderSkills();}else{const map={weapons:"weapon",armours:"armor",vehicles:"vehicle",residences:"residence",outfits:"other",武器:"weapon",防具:"armor",ヴィークル:"vehicle",住居:"residence",住宅:"residence",装備:"other"};for(const r of rows)outfits.push({...blankOutfit(),category:map[r.target]||"other",name:r.name||"",purchase_value:r.purchase||"",experience_cost:Number(r.permanent||0),concealment:[r.concealA,r.concealB].filter(Boolean).join("/"),attack:r.attack||"",defense:r.defense||"",range:r.range||"",slot:r.part||r.slot||"",description:r.notes||""});renderOutfits();}recalc();markDirty();}
function jpError(m=""){if(/characters_visibility_check/i.test(m))return"公開状態を保存できません。Supabaseの公開状態制約を更新してください。";if(/row-level security|RLS/i.test(m))return"保存権限がありません。ログイン状態を確認してください。";if(/schema cache/i.test(m))return"データベース項目を確認できません。Supabaseのスキーマを再読み込みしてください。";if(/network|fetch/i.test(m))return"通信に失敗しました。ネットワーク接続を確認してください。";return m?`保存に失敗しました：${m}`:"保存に失敗しました。";}
function pulse(s){const b=$("#save-button");b.classList.remove("is-saving","is-saved","is-error");void b.offsetWidth;b.classList.add(s==="saving"?"is-saving":s==="saved"?"is-saved":"is-error");}
function setStatus(t,s=""){const e=$("#save-status");e.textContent=t;e.className=s;}
