import { supabase } from "./supabase-client.js";

const statusNode = document.querySelector("#statistics-status");
const generatedAtNode = document.querySelector("#statistics-generated-at");
const errorNode = document.querySelector("#statistics-error");
initialize();

async function initialize() {
  try {
    setStatus("公開データ集計中");
    const { data: characters, error: characterError } = await supabase.from("characters").select(`id, public_id, player_name, affiliation, citizen_rank, experience_points, style_1, style_2, style_3, reason_value, passion_value, life_value, mundane_value, reason_control, passion_control, life_control, mundane_control, cs, updated_at`).eq("visibility", "public");
    if (characterError) throw characterError;
    const publicCharacters = characters ?? [];
    const ids = publicCharacters.map(item => item.id).filter(Boolean);
    let skills = [], outfits = [];
    if (ids.length) {
      const [skillResult, outfitResult] = await Promise.all([
        supabase.from("character_skills").select("character_id, category, name, level, reason, passion, life, mundane").in("character_id", ids),
        supabase.from("character_outfits").select("character_id, category, name").in("character_id", ids)
      ]);
      if (skillResult.error) throw skillResult.error;
      if (outfitResult.error) throw outfitResult.error;
      skills = skillResult.data ?? []; outfits = outfitResult.data ?? [];
    }
    renderStatistics(buildStatistics(publicCharacters, skills, outfits));
    generatedAtNode.textContent = `集計日時 ${formatDateTime(new Date())}`;
    setStatus(`${publicCharacters.length}件 集計完了`);
  } catch (error) {
    console.error("Statistics load failed:", error); setStatus("集計失敗");
    if (errorNode) { errorNode.hidden = false; errorNode.textContent = "統計情報を取得できませんでした。時間をおいて再度読み込んでください。"; }
  }
}

function buildStatistics(characters, skills, outfits) {
  const players=new Set(), affiliations=new Set(), styleCounts=new Map(), styleComboCounts=new Map(), affiliationCounts=new Map(), rankCounts=new Map(), generalSkillCharacters=new Map(), styleSkillCharacters=new Map(), outfitCategoryCounts=new Map(), outfitNameCounts=new Map(), skillCountByCharacter=new Map(), outfitCountByCharacter=new Map();
  const expBins=new Map([["0",0],["1–30",0],["31–60",0],["61–100",0],["101–200",0],["201+",0]]), csBins=new Map([["0–5",0],["6–8",0],["9–11",0],["12–14",0],["15+",0]]);
  const abilityTotals={reason:0,passion:0,life:0,mundane:0}, controlTotals={reason:0,passion:0,life:0,mundane:0};
  let experienceTotal=0,recent=0; const recentThreshold=Date.now()-30*24*60*60*1000;
  for(const c of characters){const p=clean(c.player_name);if(p)players.add(p);const a=clean(c.affiliation);if(a){affiliations.add(a);increment(affiliationCounts,a);}increment(rankCounts,clean(c.citizen_rank)||"未登録");const exp=numberOrZero(c.experience_points);experienceTotal+=exp;incrementExpBin(expBins,exp);incrementCsBin(csBins,numberOrZero(c.cs));abilityTotals.reason+=numberOrZero(c.reason_value);abilityTotals.passion+=numberOrZero(c.passion_value);abilityTotals.life+=numberOrZero(c.life_value);abilityTotals.mundane+=numberOrZero(c.mundane_value);controlTotals.reason+=numberOrZero(c.reason_control);controlTotals.passion+=numberOrZero(c.passion_control);controlTotals.life+=numberOrZero(c.life_control);controlTotals.mundane+=numberOrZero(c.mundane_control);const u=new Date(c.updated_at).getTime();if(Number.isFinite(u)&&u>=recentThreshold)recent++;const styles=[c.style_1,c.style_2,c.style_3].map(clean).filter(Boolean);styles.forEach(s=>increment(styleCounts,s));if(styles.length)increment(styleComboCounts,[...styles].sort(localeCompareJa).join(" × "));}
  for(const s of skills){const id=s.character_id;skillCountByCharacter.set(id,(skillCountByCharacter.get(id)??0)+1);const name=clean(s.name);if(!name)continue;const target=clean(s.category)==="style"?styleSkillCharacters:generalSkillCharacters;if(!target.has(name))target.set(name,new Set());target.get(name).add(id);}
  for(const o of outfits){const id=o.character_id;outfitCountByCharacter.set(id,(outfitCountByCharacter.get(id)??0)+1);increment(outfitCategoryCounts,normalizeOutfitCategory(o.category));const name=clean(o.name);if(name)increment(outfitNameCounts,name);}
  const divisor=Math.max(1,characters.length), abilities=mapAverage(abilityTotals,divisor), controls=mapAverage(controlTotals,divisor);
  return {total:characters.length,players:players.size,affiliations:affiliations.size,averageExp:characters.length?Math.round(experienceTotal/characters.length):0,recent,styleCounts,styleComboCounts,affiliationCounts,rankCounts,expBins,csBins,generalSkillCounts:setMapToCountMap(generalSkillCharacters),styleSkillCounts:setMapToCountMap(styleSkillCharacters),outfitCategoryCounts,outfitNameCounts,abilities,controls,averageSkillCount:averageMapCount(skillCountByCharacter,characters),averageOutfitCount:averageMapCount(outfitCountByCharacter,characters),mostCommonOutfit:topEntry(outfitNameCounts),rarestStyle:bottomEntry(styleCounts),mostCommonCombo:topEntry(styleComboCounts),highestAbility:highestNamedValue(abilities),highestControl:highestNamedValue(controls)};
}

function renderStatistics(s){setText("#stat-total-casts",s.total);setText("#stat-players",s.players);setText("#stat-affiliations",s.affiliations);setText("#stat-average-exp",s.averageExp);setText("#stat-recent",s.recent);renderRanking("#statistics-styles",s.styleCounts,{limit:20});renderRanking("#statistics-ranks",s.rankCounts,{limit:12});renderRanking("#statistics-exp",s.expBins,{preserveOrder:true});renderRanking("#statistics-affiliation-ranking",s.affiliationCounts,{limit:12});renderPodium("#statistics-general-skills",s.generalSkillCounts,10);renderPodium("#statistics-style-skills",s.styleSkillCounts,10);renderRadar(s.abilities);renderMeters(s.controls);renderHistogram(s.csBins);renderDonut(s.outfitCategoryCounts);renderStyleCombos(s.styleComboCounts);renderOddities(s);}
function renderRanking(selector,source,options={}){const root=document.querySelector(selector);if(!root)return;let entries=Array.from(source.entries());if(!options.preserveOrder)entries.sort((a,b)=>b[1]-a[1]||localeCompareJa(a[0],b[0]));if(options.limit)entries=entries.slice(0,options.limit);if(!entries.length)return renderEmpty(root);const max=Math.max(1,...entries.map(([,v])=>v));root.replaceChildren(...entries.map(([l,v])=>createRankingRow(l,v,max)));}
function createRankingRow(label,value,max){const ratio=Math.max(0,Math.min(100,value/max*100)),row=document.createElement("div");row.className="statistics-ranking__row";row.style.setProperty("--ratio",`${ratio.toFixed(2)}%`);const l=document.createElement("span");l.className="statistics-ranking__label";l.textContent=label;l.title=label;const bar=document.createElement("span");bar.className="statistics-ranking__bar";const fill=document.createElement("i");fill.style.setProperty("--ratio",`${ratio.toFixed(2)}%`);bar.append(fill);const v=document.createElement("strong");v.className="statistics-ranking__value";v.textContent=String(value);row.append(l,bar,v);return row;}
function renderPodium(selector,source,limit){const root=document.querySelector(selector);if(!root)return;const entries=Array.from(source.entries()).sort((a,b)=>b[1]-a[1]||localeCompareJa(a[0],b[0])).slice(0,limit);if(!entries.length)return renderEmpty(root);root.replaceChildren(...entries.map(([label,value],index)=>{const item=document.createElement("div");item.className=`statistics-podium__item statistics-podium__item--${Math.min(index+1,4)}`;item.innerHTML=`<b>${String(index+1).padStart(2,"0")}</b><span>${escapeHtml(label)}</span><strong>${value}人</strong>`;return item;}));}
function renderRadar(values){const root=document.querySelector("#statistics-abilities");if(!root)return;const labels=[["reason","理性"],["passion","感情"],["life","生命"],["mundane","外界"]],max=Math.max(1,...labels.map(([k])=>values[k]));root.innerHTML='<div class="statistics-radar__diamond" aria-hidden="true"></div>';labels.forEach(([k,l],i)=>{const item=document.createElement("div");item.className=`statistics-radar__axis statistics-radar__axis--${i+1}`;const meter=Math.min(100,values[k]/max*100);item.innerHTML=`<span>${l}</span><strong>${values[k].toFixed(1)}</strong><i style="--meter:${meter.toFixed(1)}%"></i>`;root.append(item);});}
function renderMeters(values){const root=document.querySelector("#statistics-controls");if(!root)return;const labels=[["reason","理性"],["passion","感情"],["life","生命"],["mundane","外界"]],max=Math.max(1,...labels.map(([k])=>values[k]));root.replaceChildren(...labels.map(([k,l])=>{const item=document.createElement("div");item.className="statistics-meter";item.style.setProperty("--meter",`${Math.min(100,values[k]/max*100).toFixed(1)}%`);item.innerHTML=`<span>${l}</span><strong>${values[k].toFixed(1)}</strong><i></i>`;return item;}));}
function renderHistogram(source){const root=document.querySelector("#statistics-cs");if(!root)return;const entries=Array.from(source.entries()),max=Math.max(1,...entries.map(([,v])=>v));root.replaceChildren(...entries.map(([l,v])=>{const item=document.createElement("div");item.className="statistics-histogram__bar";item.style.setProperty("--height",`${Math.max(5,v/max*100).toFixed(1)}%`);item.innerHTML=`<strong>${v}</strong><i></i><span>${l}</span>`;return item;}));}
function renderDonut(source){const root=document.querySelector("#statistics-outfit-mix");if(!root)return;const entries=Array.from(source.entries()).sort((a,b)=>b[1]-a[1]),total=entries.reduce((sum,[,v])=>sum+v,0);if(!total)return renderEmpty(root);const top=entries.slice(0,6),degrees=top.map(([,v])=>v/total*360);let cursor=0;const parts=degrees.map((d,i)=>{const start=cursor;cursor+=d;return`var(--donut-${i+1}) ${start.toFixed(2)}deg ${cursor.toFixed(2)}deg`;});const chart=document.createElement("div");chart.className="statistics-donut";chart.style.background=`conic-gradient(${parts.join(",")})`;chart.innerHTML=`<div><strong>${total}</strong><span>OUTFITS</span></div>`;const legend=document.createElement("div");legend.className="statistics-donut-legend";top.forEach(([l,v],i)=>{const item=document.createElement("div");item.innerHTML=`<i class="statistics-donut-key statistics-donut-key--${i+1}"></i><span>${escapeHtml(l)}</span><strong>${Math.round(v/total*100)}%</strong>`;legend.append(item);});root.replaceChildren(chart,legend);}
function renderStyleCombos(source){const root=document.querySelector("#statistics-style-combos");if(!root)return;const entries=Array.from(source.entries()).sort((a,b)=>b[1]-a[1]||localeCompareJa(a[0],b[0])).slice(0,12);if(!entries.length)return renderEmpty(root);root.replaceChildren(...entries.map(([l,v],i)=>{const item=document.createElement("div");item.className="statistics-combo-tile";item.innerHTML=`<small>#${String(i+1).padStart(2,"0")}</small><strong>${escapeHtml(l)}</strong><span>${v} CAST${v===1?"":"S"}</span>`;return item;}));}
function renderOddities(s){const root=document.querySelector("#statistics-oddities");if(!root)return;const items=[["平均技能数",`${s.averageSkillCount.toFixed(1)} 個`,"SKILLS / CAST"],["平均アウトフィット数",`${s.averageOutfitCount.toFixed(1)} 個`,"OUTFITS / CAST"],["最も希少なスタイル",s.rarestStyle?`${s.rarestStyle[0]} (${s.rarestStyle[1]})`:"—","RAREST STYLE"],["最多アウトフィット",s.mostCommonOutfit?`${s.mostCommonOutfit[0]} (${s.mostCommonOutfit[1]})`:"—","MOST COMMON OUTFIT"],["最多スタイル構成",s.mostCommonCombo?s.mostCommonCombo[0]:"—","COMMON COMBINATION"],["最も高い平均能力",`${s.highestAbility.label} ${s.highestAbility.value.toFixed(1)}`,"ABILITY PEAK"],["最も高い平均制御",`${s.highestControl.label} ${s.highestControl.value.toFixed(1)}`,"CONTROL PEAK"]];root.replaceChildren(...items.map(([l,v,e],i)=>{const item=document.createElement("article");item.className=`statistics-oddity statistics-oddity--${i%4+1}`;item.innerHTML=`<span>${l}</span><strong>${escapeHtml(v)}</strong><small>${e}</small>`;return item;}));}
function setMapToCountMap(source){return new Map(Array.from(source,([k,v])=>[k,v.size]));}function mapAverage(source,d){return Object.fromEntries(Object.entries(source).map(([k,v])=>[k,v/d]));}function averageMapCount(source,characters){if(!characters.length)return 0;return characters.reduce((sum,c)=>sum+(source.get(c.id)??0),0)/characters.length;}function highestNamedValue(values){const names={reason:"理性",passion:"感情",life:"生命",mundane:"外界"};return Object.entries(values).map(([k,v])=>({label:names[k],value:v})).sort((a,b)=>b.value-a.value)[0]??{label:"—",value:0};}function topEntry(map){return Array.from(map.entries()).sort((a,b)=>b[1]-a[1]||localeCompareJa(a[0],b[0]))[0]??null;}function bottomEntry(map){return Array.from(map.entries()).sort((a,b)=>a[1]-b[1]||localeCompareJa(a[0],b[0]))[0]??null;}
function normalizeOutfitCategory(value){const raw=clean(value).toLowerCase(),labels={weapon:"武器",armor:"防具",cyberware:"サイバーウェア",tron:"トロン",vehicle:"ヴィークル",residence:"住居",other:"その他"};return labels[raw]||clean(value)||"未分類";}function increment(map,key){map.set(key,(map.get(key)??0)+1);}function incrementExpBin(map,v){if(v<=0)increment(map,"0");else if(v<=30)increment(map,"1–30");else if(v<=60)increment(map,"31–60");else if(v<=100)increment(map,"61–100");else if(v<=200)increment(map,"101–200");else increment(map,"201+");}function incrementCsBin(map,v){if(v<=5)increment(map,"0–5");else if(v<=8)increment(map,"6–8");else if(v<=11)increment(map,"9–11");else if(v<=14)increment(map,"12–14");else increment(map,"15+");}
function setText(selector,value){const node=document.querySelector(selector);if(node)node.textContent=Number(value).toLocaleString("ja-JP");}function setStatus(value){if(statusNode)statusNode.textContent=value;}function renderEmpty(root){root.innerHTML='<p class="statistics-empty">集計対象データがありません。</p>';}function clean(value){return String(value??"").trim();}function numberOrZero(value){const n=Number(value);return Number.isFinite(n)?n:0;}function localeCompareJa(a,b){return String(a).localeCompare(String(b),"ja",{sensitivity:"base",numeric:true});}function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}function formatDateTime(date){return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(date);}
