export const STYLE_DATA = [
  { name: "カブキ", divine: "チャイ", divineYomi: "チャイ", reason:[0,3], passion:[3,5], life:[2,4], mundane:[2,4] },
  { name: "バサラ", divine: "天変地異", divineYomi: "カタストロフ", reason:[3,5], passion:[2,5], life:[1,3], mundane:[1,3] },
  { name: "タタラ", divine: "タイムリー", divineYomi: "タイムリー", reason:[3,5], passion:[1,3], life:[1,3], mundane:[2,5] },
  { name: "ミストレス", divine: "ファイト！", divineYomi: "ファイト", reason:[1,4], passion:[3,5], life:[1,2], mundane:[2,5] },
  { name: "カブト", divine: "難攻不落", divineYomi: "インヴァルネラブル", reason:[2,4], passion:[1,4], life:[3,5], mundane:[1,3] },
  { name: "カリスマ", divine: "神の御言葉", divineYomi: "ゴスペル", reason:[1,3], passion:[3,5], life:[0,3], mundane:[3,5] },
  { name: "マネキン", divine: "プリーズ！", divineYomi: "プリーズ", reason:[1,3], passion:[3,5], life:[2,5], mundane:[1,3] },
  { name: "カゼ", divine: "脱出", divineYomi: "エクソダス", reason:[2,5], passion:[1,3], life:[2,4], mundane:[2,4] },
  { name: "フェイト", divine: "真実", divineYomi: "トゥルース", reason:[2,5], passion:[2,5], life:[1,3], mundane:[2,3] },
  { name: "クロマク", divine: "腹心", divineYomi: "ライトハンド", reason:[1,3], passion:[2,5], life:[1,3], mundane:[3,5] },
  { name: "エグゼク", divine: "買収", divineYomi: "M&A", reason:[2,5], passion:[1,3], life:[1,3], mundane:[3,5] },
  { name: "カタナ", divine: "死の舞踏", divineYomi: "ダンス・マカブル", reason:[2,4], passion:[0,4], life:[3,5], mundane:[2,3] },
  { name: "クグツ", divine: "完全偽装", divineYomi: "アンダカヴァ", reason:[3,5], passion:[0,4], life:[3,5], mundane:[1,2] },
  { name: "カゲ", divine: "不可知", divineYomi: "インセンサブル", reason:[3,4], passion:[0,5], life:[2,4], mundane:[2,3] },
  { name: "チャクラ", divine: "黄泉還り", divineYomi: "フェニックス", reason:[2,5], passion:[2,5], life:[3,5], mundane:[0,1] },
  { name: "レッガー", divine: "不可触", divineYomi: "アンタッチャブル", reason:[2,4], passion:[2,4], life:[2,4], mundane:[1,4] },
  { name: "カブトワリ", divine: "とどめの一撃", divineYomi: "クーデグラ", reason:[2,4], passion:[0,4], life:[2,3], mundane:[3,5] },
  { name: "ハイランダー", divine: "天罰", divineYomi: "ネメシス", reason:[2,5], passion:[2,5], life:[0,1], mundane:[3,5] },
  { name: "マヤカシ", divine: "守護神", divineYomi: "ガーディアン", reason:[3,5], passion:[3,5], life:[0,2], mundane:[1,4] },
  { name: "トーキー", divine: "暴露", divineYomi: "エクスポーズ", reason:[2,5], passion:[3,5], life:[1,3], mundane:[1,3] },
  { name: "イヌ", divine: "制裁", divineYomi: "パニッシュ", reason:[3,5], passion:[1,3], life:[2,5], mundane:[1,3] },
  { name: "ニューロ", divine: "電脳神", divineYomi: "デウス・エクス・マキナ", reason:[3,5], passion:[2,5], life:[0,1], mundane:[2,5] },
  { name: "コモン", divine: "平和", divineYomi: "ピース", reason:[1,3], passion:[2,4], life:[2,4], mundane:[2,5] },
  { name: "ヒルコ", divine: "突然変異", divineYomi: "ミューテイション", reason:[1,3], passion:[3,5], life:[3,5], mundane:[0,3] },
  { name: "クロガネ", divine: "万能道具", divineYomi: "マスターピース", reason:[3,5], passion:[2,4], life:[2,4], mundane:[0,3] },
  { name: "イブキ", divine: "人命救助", divineYomi: "アセンドライフ", reason:[1,4], passion:[2,3], life:[3,5], mundane:[1,4] },
  { name: "シキガミ", divine: "友情", divineYomi: "フレンドシップ", reason:[2,5], passion:[2,4], life:[2,5], mundane:[1,2] },
  { name: "アラシ", divine: "突破", divineYomi: "ブレイクスルー", reason:[3,5], passion:[0,3], life:[1,3], mundane:[3,5] },
  { name: "カゲムシャ", divine: "神出鬼没", divineYomi: "チェンジ", reason:[2,4], passion:[3,5], life:[2,4], mundane:[0,3] },
  { name: "ミギウデ", divine: "半身", divineYomi: "ベターハーフ", reason:[2,4], passion:[2,4], life:[2,5], mundane:[1,3] },
  { name: "エトランゼ", divine: "超越品", divineYomi: "ハイパーアイテム", reason:[3,5], passion:[1,4], life:[0,2], mundane:[3,5] },
  { name: "アヤカシ", divine: "霧散", divineYomi: "ディスペア", reason:[0,5], passion:[1,5], life:[3,2], mundane:[3,4] },
  { name: "ウツワ", divine: "神意", divineYomi: "ミラクル", special: "utsuwa" }
];

export const UTSUWA_ATTRIBUTES = [
  { name:"雷神", reason:[3,5], passion:[1,3], life:[1,3], mundane:[2,5] },
  { name:"太陽神", reason:[2,4], passion:[2,4], life:[1,4], mundane:[2,4] },
  { name:"月神", reason:[2,5], passion:[3,5], life:[1,3], mundane:[1,3] },
  { name:"海洋神", reason:[1,3], passion:[2,4], life:[3,5], mundane:[1,4] },
  { name:"大地神", reason:[2,4], passion:[1,4], life:[3,5], mundane:[1,3] },
  { name:"冥府神", reason:[1,3], passion:[2,3], life:[2,5], mundane:[2,5] },
  { name:"火神", reason:[2,5], passion:[2,4], life:[2,4], mundane:[1,3] },
  { name:"美神", reason:[0,2], passion:[3,5], life:[1,4], mundane:[3,5] },
  { name:"道化神", reason:[1,3], passion:[3,5], life:[2,4], mundane:[1,4] },
  { name:"運命神", reason:[2,4], passion:[2,4], life:[0,3], mundane:[3,5] },
  { name:"智神", reason:[3,5], passion:[2,5], life:[0,2], mundane:[2,4] },
  { name:"軍神", reason:[3,5], passion:[0,3], life:[3,5], mundane:[1,3] },
  { name:"風神", reason:[2,4], passion:[2,5], life:[3,5], mundane:[0,2] },
  { name:"司法神", reason:[2,5], passion:[1,3], life:[2,4], mundane:[2,4] },
  { name:"商業神", reason:[1,3], passion:[1,4], life:[2,4], mundane:[3,5] },
  { name:"策謀神", reason:[3,5], passion:[1,2], life:[0,4], mundane:[3,5] },
  { name:"伝令神", reason:[3,5], passion:[2,4], life:[1,3], mundane:[1,4] }
];