import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createQuickSheetHtml, createQuickPageHeader, createQuickPageFooter } from '../js/cast-quick-sheet-html.js';
import { renderShowcase } from '../js/showcase-output-html.js';
import { quickCases, showcaseCases, usageEntries, baseUrl } from './fixtures/output-rendering.mjs';

// SHA256 of full HTML generated by the pre-extraction implementation at 54a5357.
// Captured using these synthetic fixtures; whitespace and escaping are part of the contract.
const quickHashes = {
  empty: '33f84ede3f8c7025e3f8bd73b7be1be9572c29417a74a211c3540149ed0a4ddc',
  mixed: '1ede31db1d3629bc2092921c25f7633b568b0d047d2b554489df8fbb8dd2a6d4',
  long: '346f0fff58185439fad4837d02fedbf99c6d28a9922d8647914332db2a112914'
};
const showcaseHashes = {
  'nova-plain': '04d73f1e7a31dd161b5ffa670250beb6641fc81637e3b667d95f175f8fa284b0',
  'nova-background': 'ac1156647a6700dfc4abbd38c3c843f553a46ef6dd09e2ef3213ade0fc3965e3',
  'intron-plain': 'c2e4ae56019d9a631c49892d751e2440402b4fed2738d3038b043a71b5026ad7',
  'intron-background': '481d0b5e5cbe25717a8f2c113396466ecdaa3c7c4ce6a613cf6cff4e9a5378ff',
  'vlad-plain': 'c53facb358a76caf1724bcdbf91b8a7d0836cb479ebcbbfa5a1082ad870db00d',
  'vlad-background': '79ad7707e82d4f63785e480079ec4c19f2f179624c5b6e84605c88be2659b8a3',
  'lutetia-plain': '820d8c32fabe0dabd43c259b37fe7e5cebc75240196aa171c9be792e57d5ed87',
  'lutetia-background': '0d1d282109e2a8106fc0b5369190f918218c0fb88e4d44c6e4ef7d9baf1493da',
  'unknown-plain': '04d73f1e7a31dd161b5ffa670250beb6641fc81637e3b667d95f175f8fa284b0',
  'unknown-background': 'ac1156647a6700dfc4abbd38c3c843f553a46ef6dd09e2ef3213ade0fc3965e3'
};
const hash = html => createHash('sha256').update(html).digest('hex');
for (const { name, data } of quickCases) {
  test(`quick-sheet HTML is unchanged: ${name}`, () => {
    const before = structuredClone(data);
    assert.equal(hash(createQuickSheetHtml(data, new Map(usageEntries))), quickHashes[name]);
    assert.deepEqual(data, before, 'rendering must not mutate input');
  });
}
for (const { name, data } of showcaseCases) {
  test(`standalone showcase HTML is unchanged: ${name}`, () => {
    const before = structuredClone(data);
    assert.equal(hash(renderShowcase(data, baseUrl)), showcaseHashes[name]);
    assert.deepEqual(data, before);
  });
}
test('usage state is supplied explicitly and continuation headers remain available', () => {
  const data = quickCases[1].data;
  assert.match(createQuickSheetHtml(data, new Map(usageEntries)), /使用 2\/3/);
  assert.match(createQuickSheetHtml(data), /使用 0\/3/);
  assert.match(createQuickSheetHtml(data, new Map(usageEntries)), /<b>1 \/ 2<\/b>/);
  assert.match(createQuickPageHeader(data.character, 4), /<b>4 \/ 3<\/b>/);
  assert.match(createQuickPageFooter(4), /PAGE 4 \/ 3/);
});
test('private and manual cards do not expose cast links or private IDs', () => {
  const data = showcaseCases[0].data;
  const html = renderShowcase(data, baseUrl);
  assert.equal((html.match(/OPEN CAST DATABASE →/g) || []).length, 1);
  assert.match(html, /PRIVATE CAST \/\/ LOCAL OUTPUT/);
  assert.match(html, /CAST DATABASE \/\/ SCAN FAILED/);
  assert.doesNotMatch(html, /PRIVATE-SECRET/);
  assert.match(html, /https:\/\/example\.test\/archive\/cast\.html\?id=TNX-FIXTURE/);
  assert.match(renderShowcase(data, 'https://example.test/other/generator.html'), /https:\/\/example\.test\/other\/cast\.html\?id=TNX-FIXTURE/);
});
test('HTML modules cannot read browser state or persistence directly', () => {
  for (const file of ['cast-quick-sheet-html.js', 'showcase-output-html.js', 'cast-display-format.js']) {
    const source = readFileSync(new URL(`../js/${file}`, import.meta.url), 'utf8');
    assert.doesNotMatch(source, /\b(?:window|document|location|localStorage|supabase)\s*[.[]/);
    assert.doesNotMatch(source, /import.*(?:cast\.js|supabase-client|auth-state)/);
  }
});
