import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createQuickSheetHtml, createQuickPageHeader, createQuickPageFooter } from '../js/cast-quick-sheet-html.js';
import { renderShowcase } from '../js/showcase-output-html.js';
import { quickCases, showcaseCases, usageEntries, baseUrl } from './fixtures/output-rendering.mjs';

// SHA256 of full HTML generated by the pre-extraction implementation at 54a5357.
// Captured using these synthetic fixtures; whitespace and escaping are part of the contract.
const quickHashes = {
  empty: '33f84ede3f8c7025e3f8bd73b7be1be9572c29417a74a211c3540149ed0a4ddc',
  mixed: '1ede31db1d3629bc2092921c25f7633b568b0d047d2b554489df8fbb8dd2a6d4',
  long: '346f0fff58185439fad4837d02fedbf99c6d28a9922d8647914332db2a112914'
};
const showcaseHashes = {
  'nova-plain': '6aecfd2c7286173f54ac4ab17804d0fb2572d2648abd6938c8de0d7b00c538d1',
  'nova-background': '5f4e9609113c3e18811c41ba080ef1f5835b1392e2eab70c74546308b8e70b3a',
  'intron-plain': '5c8bc4ef380b96953f6de952396cbd29366045f123f6c71af9b49d317c38a422',
  'intron-background': 'c50b3e68b745b1b918549216972180485d2d1ee416d04e66ba45559629d7e086',
  'vlad-plain': '0858527282f1cbf48f2c770ba1a44bdc973b8e43bf9853d7c3b6ee966e733465',
  'vlad-background': 'a77b2450f63496f5d972044cfc761e68759f740dd14d1aff067dd9a882faceea',
  'lutetia-plain': '2f00abd0d6c8e0d612b391b039b52782894f28519f98c8b58b371fcc3ac1a5dd',
  'lutetia-background': 'ead0e2ebff58a6f57d404f8fca8059eb7e0def6ce9383df8a660b3aecb67e74c',
  'unknown-plain': '6aecfd2c7286173f54ac4ab17804d0fb2572d2648abd6938c8de0d7b00c538d1',
  'unknown-background': '5f4e9609113c3e18811c41ba080ef1f5835b1392e2eab70c74546308b8e70b3a'
};
const hash = html => createHash('sha256').update(html).digest('hex');
for (const { name, data } of quickCases) {
  test(`quick-sheet HTML is unchanged: ${name}`, () => {
    const before = structuredClone(data);
    assert.equal(hash(createQuickSheetHtml(data, new Map(usageEntries))), quickHashes[name]);
    assert.deepEqual(data, before, 'rendering must not mutate input');
  });
}
for (const { name, data } of showcaseCases) {
  test(`standalone showcase HTML is unchanged: ${name}`, () => {
    const before = structuredClone(data);
    assert.equal(hash(renderShowcase(data, baseUrl)), showcaseHashes[name]);
    assert.deepEqual(data, before);
  });
}
test('usage state is supplied explicitly and continuation headers remain available', () => {
  const data = quickCases[1].data;
  assert.match(createQuickSheetHtml(data, new Map(usageEntries)), /使用 2\/3/);
  assert.match(createQuickSheetHtml(data), /使用 0\/3/);
  assert.match(createQuickSheetHtml(data, new Map(usageEntries)), /<b>1 \/ 2<\/b>/);
  assert.match(createQuickPageHeader(data.character, 4), /<b>4 \/ 3<\/b>/);
  assert.match(createQuickPageFooter(4), /PAGE 4 \/ 3/);
});
test('private and manual cards do not expose cast links or private IDs', () => {
  const data = showcaseCases[0].data;
  const html = renderShowcase(data, baseUrl);
  assert.equal((html.match(/OPEN CAST DATABASE →/g) || []).length, 1);
  assert.match(html, /PRIVATE CAST \/\/ LOCAL OUTPUT/);
  assert.match(html, /CAST DATABASE \/\/ SCAN FAILED/);
  assert.doesNotMatch(html, /PRIVATE-SECRET/);
  assert.match(html, /https:\/\/example\.test\/archive\/cast\.html\?id=TNX-FIXTURE/);
  assert.match(renderShowcase(data, 'https://example.test/other/generator.html'), /https:\/\/example\.test\/other\/cast\.html\?id=TNX-FIXTURE/);
});
test('HTML modules cannot read browser state or persistence directly', () => {
  for (const file of ['cast-quick-sheet-html.js', 'showcase-output-html.js', 'cast-display-format.js']) {
    const source = readFileSync(new URL(`../js/${file}`, import.meta.url), 'utf8');
    assert.doesNotMatch(source, /\b(?:window|document|location|localStorage|supabase)\s*[.[]/);
    assert.doesNotMatch(source, /import.*(?:cast\.js|supabase-client|auth-state)/);
  }
});
