import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createQuickSheetHtml, createQuickPageHeader, createQuickPageFooter } from '../js/cast-quick-sheet-html.js';
import { renderShowcase } from '../js/showcase-output-html.js';
import { quickCases, showcaseCases, usageEntries, baseUrl } from './fixtures/output-rendering.mjs';

// SHA256 of full HTML generated by the pre-extraction implementation at 54a5357.
// Captured using these synthetic fixtures; whitespace and escaping are part of the contract.
const quickHashes = {
  empty: '33f84ede3f8c7025e3f8bd73b7be1be9572c29417a74a211c3540149ed0a4ddc',
  mixed: '1ede31db1d3629bc2092921c25f7633b568b0d047d2b554489df8fbb8dd2a6d4',
  long: '346f0fff58185439fad4837d02fedbf99c6d28a9922d8647914332db2a112914'
};
const showcaseHashes = {
  'nova-plain': 'e49f2b72159f85a215817817364a9dfdb25efb0510b77ad7dd9c553f80df3066',
  'nova-background': 'f7b83c63888ca61436895cb313f44a4bc39f41fcf6fea76f9a56cafdd1b8d92e',
  'intron-plain': '4e56adebc89257cfa7b2339b54496f49962842595675ba22b33a81d328e60432',
  'intron-background': 'ef68ef1cc412c4bd2066da9914404d0439b328ef348802eaf183773361c66648',
  'vlad-plain': 'df2d8359c2b70412bd678d4deb18f726b0484e86e4eeba31c241615c470cd843',
  'vlad-background': 'f9c6addb403b07e0176c79938bf774ac822ce24ac1ae18865f7a27781bcb720e',
  'lutetia-plain': 'b38096843a1f50c177eefbd8305453fdabf4f71c90e7cb3823527eeb2b0c842e',
  'lutetia-background': '23d3dfa81a4cf6e0fda8d805bc2403bc0a6ae1ad9215fd107f37bc2bcf045874',
  'unknown-plain': 'e49f2b72159f85a215817817364a9dfdb25efb0510b77ad7dd9c553f80df3066',
  'unknown-background': 'f7b83c63888ca61436895cb313f44a4bc39f41fcf6fea76f9a56cafdd1b8d92e'
};
const hash = html => createHash('sha256').update(html).digest('hex');
for (const { name, data } of quickCases) {
  test(`quick-sheet HTML is unchanged: ${name}`, () => {
    const before = structuredClone(data);
    assert.equal(hash(createQuickSheetHtml(data, new Map(usageEntries))), quickHashes[name]);
    assert.deepEqual(data, before, 'rendering must not mutate input');
  });
}
for (const { name, data } of showcaseCases) {
  test(`standalone showcase HTML is unchanged: ${name}`, () => {
    const before = structuredClone(data);
    assert.equal(hash(renderShowcase(data, baseUrl)), showcaseHashes[name]);
    assert.deepEqual(data, before);
  });
}
test('usage state is supplied explicitly and continuation headers remain available', () => {
  const data = quickCases[1].data;
  assert.match(createQuickSheetHtml(data, new Map(usageEntries)), /使用 2\/3/);
  assert.match(createQuickSheetHtml(data), /使用 0\/3/);
  assert.match(createQuickSheetHtml(data, new Map(usageEntries)), /<b>1 \/ 2<\/b>/);
  assert.match(createQuickPageHeader(data.character, 4), /<b>4 \/ 3<\/b>/);
  assert.match(createQuickPageFooter(4), /PAGE 4 \/ 3/);
});
test('private and manual cards do not expose cast links or private IDs', () => {
  const data = showcaseCases[0].data;
  const html = renderShowcase(data, baseUrl);
  assert.equal((html.match(/OPEN CAST DATABASE →/g) || []).length, 1);
  assert.match(html, /PRIVATE CAST \/\/ LOCAL OUTPUT/);
  assert.match(html, /CAST DATABASE \/\/ SCAN FAILED/);
  assert.doesNotMatch(html, /PRIVATE-SECRET/);
  assert.match(html, /https:\/\/example\.test\/archive\/cast\.html\?id=TNX-FIXTURE/);
  assert.match(renderShowcase(data, 'https://example.test/other/generator.html'), /https:\/\/example\.test\/other\/cast\.html\?id=TNX-FIXTURE/);
});
test('HTML modules cannot read browser state or persistence directly', () => {
  for (const file of ['cast-quick-sheet-html.js', 'showcase-output-html.js', 'cast-display-format.js']) {
    const source = readFileSync(new URL(`../js/${file}`, import.meta.url), 'utf8');
    assert.doesNotMatch(source, /\b(?:window|document|location|localStorage|supabase)\s*[.[]/);
    assert.doesNotMatch(source, /import.*(?:cast\.js|supabase-client|auth-state)/);
  }
});
