import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read = path => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("PC outfit layout has one canonical presentation owner", async () => {
  const features = await read("js/sheet-features.js");
  const display = await read("js/outfit-display-rules-v5.js");

  assert.doesNotMatch(features, /initializeArmorOutfitColumns/);
  assert.match(display, /Canonical PC outfit layout controller/);
  assert.match(display, /\["base","control_modifier","制御値"\]/);
  assert.match(display, /\["base","cs_modifier","CS修正"\]/);
  assert.doesNotMatch(display, /\["ofc","control_value"|\["ofc","cs_value"|\["base","mundane_modifier"/);
});

test("PC OFC fields are generated by the initial renderer according to category semantics", async () => {
  const renderer = await read("js/sheet-outfit-renderer.js");
  const fields = await read("js/outfit-ofc-fields.js");

  assert.match(renderer, /cyberware:\s*\[[\s\S]*electronic_control[\s\S]*ianus_surface[\s\S]*ianus_deep[\s\S]*ianus_none/);
  assert.match(renderer, /tron:\s*\[[\s\S]*electronic_control[\s\S]*tron_software[\s\S]*tron_support[\s\S]*tron_hardware/);
  assert.match(renderer, /vehicle:\s*\[[\s\S]*control_modifier[\s\S]*cs_modifier[\s\S]*defense_s[\s\S]*defense_p[\s\S]*defense_i[\s\S]*crew[\s\S]*sf/);
  assert.match(renderer, /residence:\s*\[[\s\S]*residence_entry[\s\S]*residence_electric[\s\S]*residence_area/);
  assert.doesNotMatch(fields, /createElement\(["']td["']\)|createElement\(["']th["']\)|supabase/);
});

test("OFC compatibility state preserves detail values on save without owning DOM generation", async () => {
  const fields = await read("js/outfit-ofc-fields.js");
  const save = await read("js/outfit-ofc-save.js");

  assert.match(fields, /globalThis\.TNXOutfitOFCState/);
  assert.match(fields, /parseEmbeddedDetails/);
  assert.match(save, /TNXOutfitOFCState\?\.getDetails/);
  assert.doesNotMatch(save, /details\.control_value\s*=/);
});
